"use client";
/* eslint-disable @next/next/no-img-element */
import {useEffect,useMemo,useRef,useState} from "react";
import BlogBlocks from "@/app/components/BlogBlocks";
import BlogSiteNav from "@/app/components/BlogSiteNav";
import {supabase} from "@/lib/supabase";
import {newBlock,type BlogBlock,type BlogBlockType,type BlogPost} from "@/lib/blog";

type Category={id:string;name:string};
const blank=():BlogPost=>({id:"",title:"",slug:"",excerpt:"",category:"Treatment Guide",service_category_id:null,hero_url:null,hero_type:"image",embed_url:null,blocks:[],status:"draft",featured:false,published_at:null,updated_at:""});
const types:{type:BlogBlockType;label:string;icon:string}[]=[
 {type:"paragraph",label:"Text",icon:"fa-align-left"},{type:"heading",label:"Heading",icon:"fa-heading"},{type:"image",label:"Image",icon:"fa-image"},{type:"video",label:"Video",icon:"fa-video"},{type:"list",label:"List",icon:"fa-list"},{type:"quote",label:"Quote",icon:"fa-quote-left"},{type:"faq",label:"FAQ",icon:"fa-circle-question"},{type:"cta",label:"Call to action",icon:"fa-bullhorn"},{type:"embed",label:"Embed",icon:"fa-code"},{type:"divider",label:"Divider",icon:"fa-minus"},
];
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
async function token(){const{data}=await supabase.auth.getSession();if(!data.session)throw new Error("Your session expired.");return data.session.access_token}
function Media({url,type,title}:{url:string|null;type:"image"|"video";title:string}){return url?(type==="video"?<video src={url} controls/>:<img src={url} alt={title}/>):<div className="builder-media-empty"><i className="fa-regular fa-image"/><span>Cover preview</span></div>}
function Preview({draft,mobile,hero}:{draft:BlogPost;mobile:boolean;hero:string|null}){const title=draft.title||"Your blog title",excerpt=draft.excerpt||"Your short blog summary will appear here.";return <div className={`builder-preview ${mobile?"is-mobile":""}`}><div className="builder-article-preview"><BlogSiteNav/><div className="public-article-back"><span><i className="fa-solid fa-arrow-left"/> Back to blogs on the landing page</span><span>View all blogs <i className="fa-solid fa-table-cells-large"/></span></div><header><Media url={hero||draft.hero_url} type={draft.hero_type} title={title}/><div><small>{draft.category}</small><h1>{title}</h1><p>{excerpt}</p><span>By Dr. Kharyl · The Klinique</span></div></header>{draft.embed_url&&<iframe className="public-article-featured-embed" src={draft.embed_url} title="Featured media preview"/>}{draft.blocks.length?<BlogBlocks blocks={draft.blocks}/>:<div className="builder-preview-empty"><i className="fa-solid fa-layer-group"/> Add blog sections to see them here.</div>}</div></div>}

export default function BlogBuilder(){
 const[posts,setPosts]=useState<BlogPost[]>([]),[draft,setDraft]=useState<BlogPost>(blank),[categories,setCategories]=useState<Category[]>([]),[busy,setBusy]=useState(""),[notice,setNotice]=useState<{text:string;error?:boolean}|null>(null),[mobile,setMobile]=useState(false),[heroPreview,setHeroPreview]=useState<string|null>(null),[blockPreviews,setBlockPreviews]=useState<Record<string,string>>({});
 const objectUrls=useRef<string[]>([]);
 async function load(){const auth=await token(),[a,c]=await Promise.all([fetch("/api/blog-posts?manage=1",{headers:{Authorization:`Bearer ${auth}`}}),fetch("/api/booking-catalog")]),articles=await a.json(),catalog=await c.json();if(!a.ok)throw new Error(articles.error);setPosts(articles.posts||[]);setCategories(catalog.categories||[])}
 useEffect(()=>{const frame=requestAnimationFrame(()=>void load().catch(error=>setNotice({text:error instanceof Error?error.message:"Unable to load articles.",error:true})));return()=>cancelAnimationFrame(frame)},[]);
 useEffect(()=>()=>objectUrls.current.forEach(URL.revokeObjectURL),[]);
 const update=(values:Partial<BlogPost>)=>setDraft(current=>({...current,...values}));
 const changeBlock=(id:string,values:Partial<BlogBlock>)=>setDraft(current=>({...current,blocks:current.blocks.map(block=>block.id===id?{...block,...values}:block)}));
 const choose=(post:BlogPost)=>{setDraft(post);setHeroPreview(null);setBlockPreviews({});setNotice(null);scrollTo({top:0,behavior:"smooth"})};
 const add=(type:BlogBlockType)=>update({blocks:[...draft.blocks,newBlock(type)]});
 const move=(index:number,by:number)=>{const next=[...draft.blocks],to=index+by;if(to<0||to>=next.length)return;[next[index],next[to]]=[next[to],next[index]];update({blocks:next})};
 const words=useMemo(()=>[draft.title,draft.excerpt,...draft.blocks.flatMap(block=>[block.title||"",block.text||"",...(block.items||[])])].join(" ").trim().split(/\s+/).filter(Boolean).length,[draft]);
 async function upload(file:File,blockId?:string){const local=URL.createObjectURL(file);objectUrls.current.push(local);if(blockId)setBlockPreviews(value=>({...value,[blockId]:local}));else setHeroPreview(local);setBusy(blockId||"hero");setNotice(null);try{const form=new FormData();form.append("file",file);const response=await fetch("/api/blog-media",{method:"POST",headers:{Authorization:`Bearer ${await token()}`},body:form}),result=await response.json();if(!response.ok)throw new Error(result.error);if(blockId){changeBlock(blockId,{url:result.url,type:result.type});setBlockPreviews(value=>{const next={...value};delete next[blockId];return next})}else{update({hero_url:result.url,hero_type:result.type});setHeroPreview(null)}setNotice({text:"Media uploaded and ready."})}catch(error){setNotice({text:error instanceof Error?error.message:"Upload failed.",error:true})}finally{setBusy("")}}
 async function save(status:BlogPost["status"]){setBusy("save");setNotice(null);try{const response=await fetch("/api/blog-posts",{method:draft.id?"PATCH":"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await token()}`},body:JSON.stringify({...draft,status,serviceCategoryId:draft.service_category_id,heroUrl:draft.hero_url,heroType:draft.hero_type,embedUrl:draft.embed_url,publishedAt:draft.published_at})}),result=await response.json();if(!response.ok)throw new Error(result.error);setDraft(result.post);await load();setNotice({text:status==="published"?"Article published and visible on the website.":"Draft saved."})}catch(error){setNotice({text:error instanceof Error?error.message:"Unable to save.",error:true})}finally{setBusy("")}}
 async function remove(post:BlogPost){if(!confirm(`Delete ${post.title}?`))return;const response=await fetch("/api/blog-posts",{method:"DELETE",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await token()}`},body:JSON.stringify({id:post.id})});if(!response.ok){setNotice({text:"Unable to delete the article.",error:true});return}if(draft.id===post.id)setDraft(blank());await load()}
 return <div className="blog-builder blog-studio-builder">
  <header className="studio-heading"><div><p>WEBSITE / BLOG STUDIO</p><h1>Build a beautiful blog</h1><span>Write, arrange, and preview exactly what patients will see.</span></div><div><button onClick={()=>choose(blank())}><i className="fa-solid fa-plus"/> New blog</button>{draft.id&&draft.status==="published"&&<a href={`/blog/${draft.slug}`} target="_blank" rel="noreferrer">View live <i className="fa-solid fa-arrow-up-right-from-square"/></a>}</div></header>
  {notice&&<div className={`studio-notice ${notice.error?"error":"success"}`}><i className={`fa-solid ${notice.error?"fa-circle-exclamation":"fa-circle-check"}`}/><span>{notice.text}</span><button onClick={()=>setNotice(null)}>×</button></div>}
  <div className="studio-layout"><main className="studio-editor">
   <section className="studio-card"><CardTitle number="01" title="Article details" text="The information readers see first."/><div className="blog-fields"><label className="wide">Article title<input value={draft.title} onChange={event=>update({title:event.target.value,slug:draft.id?draft.slug:slugify(event.target.value)})} placeholder="e.g. Your guide to laser treatment"/></label><label>Article URL<div className="studio-slug"><span>/blog/</span><input value={draft.slug} onChange={event=>update({slug:slugify(event.target.value)})}/></div></label><label>Content type<select value={draft.category} onChange={event=>update({category:event.target.value})}>{["Treatment Guide","Patient Education","Clinic Update","Wellness","Before & After"].map(value=><option key={value}>{value}</option>)}</select></label><label className="wide">Short summary<textarea maxLength={240} value={draft.excerpt} onChange={event=>update({excerpt:event.target.value})} placeholder="Tell readers what they will learn."/><small>{draft.excerpt.length}/240</small></label><label className="wide">Related treatment<select value={draft.service_category_id||""} onChange={event=>update({service_category_id:event.target.value||null})}><option value="">General article</option>{categories.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></label></div></section>
   <section className="studio-card"><CardTitle number="02" title="Cover media" text="Shown on the landing page and at the top of the article."/><label className={`studio-cover ${busy==="hero"?"uploading":""}`}><Media url={heroPreview||draft.hero_url} type={draft.hero_type} title="Article cover"/><span><i className={`fa-solid ${busy==="hero"?"fa-spinner fa-spin":"fa-camera"}`}/> {busy==="hero"?"Uploading…":draft.hero_url?"Replace cover":"Choose image, GIF, or video"}</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm" onChange={event=>event.target.files?.[0]&&void upload(event.target.files[0])}/></label><label className="studio-field">Optional video or embed URL<input value={draft.embed_url||""} onChange={event=>update({embed_url:event.target.value})} placeholder="https://youtube.com/..."/></label></section>
   <section className="studio-card"><CardTitle number="03" title="Build your story" text="Add sections, then arrange them in reading order."/><div className="studio-block-picker">{types.map(item=><button key={item.type} onClick={()=>add(item.type)}><i className={`fa-solid ${item.icon}`}/><span>{item.label}</span></button>)}</div><div className="blog-block-list">{draft.blocks.map((block,index)=><BlockEditor key={block.id} block={block} index={index} total={draft.blocks.length} preview={blockPreviews[block.id]} busy={busy===block.id} change={values=>changeBlock(block.id,values)} move={by=>move(index,by)} remove={()=>update({blocks:draft.blocks.filter(item=>item.id!==block.id)})} upload={file=>void upload(file,block.id)}/>)}{!draft.blocks.length&&<div className="studio-block-empty"><i className="fa-solid fa-wand-magic-sparkles"/><strong>Start building your article</strong><span>Choose a block above. The preview updates as you type.</span></div>}</div></section>
  </main><aside className="studio-preview-panel"><div className="studio-preview-tools"><strong><i className="fa-regular fa-eye"/> Live blog preview</strong><div><button className={!mobile?"active":""} onClick={()=>setMobile(false)} aria-label="Desktop"><i className="fa-solid fa-desktop"/></button><button className={mobile?"active":""} onClick={()=>setMobile(true)} aria-label="Mobile"><i className="fa-solid fa-mobile-screen"/></button></div></div><div className="studio-preview-stage"><Preview draft={draft} mobile={mobile} hero={heroPreview}/></div><div className="studio-publish"><div><span className={`blog-status ${draft.status}`}>{draft.status}</span><small>{words} words · {draft.blocks.length} sections</small></div><label><input type="checkbox" checked={draft.featured} onChange={event=>update({featured:event.target.checked})}/> Feature this blog on the home page</label><div><button disabled={busy==="save"||!draft.title||!draft.slug} onClick={()=>void save("draft")}><i className="fa-regular fa-floppy-disk"/> Save draft</button><button className="publish" disabled={busy==="save"||!draft.title||!draft.slug} onClick={()=>void save("published")}><i className={`fa-solid ${busy==="save"?"fa-spinner fa-spin":"fa-globe"}`}/> Publish blog</button></div></div></aside></div>
  <section className="blog-library"><div className="studio-library-title"><div><p>CONTENT LIBRARY</p><h2>Your articles</h2></div><span>{posts.length} total</span></div><div className="studio-library-grid">{posts.map(post=><article key={post.id}>{post.hero_url?(post.hero_type==="video"?<video src={post.hero_url} muted/>:<img src={post.hero_url} alt=""/>):<span className="studio-thumb-empty"><i className="fa-regular fa-image"/></span>}<div><small><span className={`blog-status ${post.status}`}>{post.status}</span>{post.category}</small><strong>{post.title}</strong><span>/blog/{post.slug}</span></div><button onClick={()=>choose(post)}>Edit</button><button className="delete" onClick={()=>void remove(post)} aria-label={`Delete ${post.title}`}><i className="fa-regular fa-trash-can"/></button></article>)}</div>{!posts.length&&<p className="studio-library-empty">No articles yet. Create your first story above.</p>}</section>
 </div>
}

function CardTitle({number,title,text}:{number:string;title:string;text:string}){return <div className="studio-card-title"><span>{number}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
function BlockEditor({block,index,total,preview,busy,change,move,remove,upload}:{block:BlogBlock;index:number;total:number;preview?:string;busy:boolean;change:(value:Partial<BlogBlock>)=>void;move:(by:number)=>void;remove:()=>void;upload:(file:File)=>void}){const info=types.find(item=>item.type===block.type);return <article className="studio-block"><header><span>{index+1}</span><i className={`fa-solid ${info?.icon}`}/><strong>{info?.label}</strong><div><button disabled={!index} onClick={()=>move(-1)} aria-label="Move up"><i className="fa-solid fa-arrow-up"/></button><button disabled={index===total-1} onClick={()=>move(1)} aria-label="Move down"><i className="fa-solid fa-arrow-down"/></button><button className="delete" onClick={remove} aria-label="Delete"><i className="fa-regular fa-trash-can"/></button></div></header><label className="studio-layout-select">Width<select value={block.layout||"wide"} onChange={event=>change({layout:event.target.value as BlogBlock["layout"]})}><option value="wide">Article</option><option value="full">Full</option><option value="split">Compact</option></select></label>{!(["divider","image","video"] as BlogBlockType[]).includes(block.type)&&<input value={block.title||""} onChange={event=>change({title:event.target.value})} placeholder={block.type==="faq"?"Question":"Heading or label"}/>} {["paragraph","quote","faq","cta"].includes(block.type)&&<textarea value={block.text||""} onChange={event=>change({text:event.target.value})} placeholder={block.type==="faq"?"Answer…":"Write your content…"}/>} {block.type==="list"&&<textarea value={(block.items||[]).join("\n")} onChange={event=>change({items:event.target.value.split("\n")})} placeholder="One item per line"/>} {(["image","video"] as BlogBlockType[]).includes(block.type)&&<label className="studio-inline-media">{preview||block.url?(block.type==="video"?<video src={preview||block.url} controls/>:<img src={preview||block.url} alt={block.alt||"Article media"}/>):<span><i className={`fa-solid ${busy?"fa-spinner fa-spin":"fa-cloud-arrow-up"}`}/> Upload {block.type}</span>}<input type="file" accept={block.type==="video"?"video/mp4,video/webm":"image/jpeg,image/png,image/webp,image/gif"} onChange={event=>event.target.files?.[0]&&upload(event.target.files[0])}/></label>} {block.type==="image"&&<input value={block.alt||""} onChange={event=>change({alt:event.target.value})} placeholder="Image description for accessibility"/>} {block.type==="embed"&&<input value={block.url||""} onChange={event=>change({url:event.target.value})} placeholder="YouTube or public embed URL"/>} {block.type==="cta"&&<div className="studio-cta-fields"><input value={block.buttonLabel||""} onChange={event=>change({buttonLabel:event.target.value})} placeholder="Button label"/><input value={block.buttonUrl||""} onChange={event=>change({buttonUrl:event.target.value})} placeholder="Button URL"/></div>}</article>}
