"use client";

import { useState } from "react";
import { supabase } from "@/lib/supabase";

export type TaxonomyCategory = { id:string; name:string; slug:string; sort_order?:number; calendar_color?:string };
export type TaxonomySubcategory = TaxonomyCategory & { category_id:string };

async function taxonomyApi(method:string,body:Record<string,unknown>){
  const {data}=await supabase.auth.getSession(); if(!data.session)throw new Error("Your session expired. Please sign in again.");
  const response=await fetch("/api/catalog-taxonomy",{method,headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify(body)}); const result=await response.json(); if(!response.ok)throw new Error(result.error||"Unable to update catalog definitions."); return result;
}

export default function CatalogTaxonomyManager({serviceCategories,serviceSubcategories,packageCategories,packageSubcategories,onChanged}:{serviceCategories:TaxonomyCategory[];serviceSubcategories:TaxonomySubcategory[];packageCategories:TaxonomyCategory[];packageSubcategories:TaxonomySubcategory[];onChanged:()=>Promise<void>}){
  const [newCategory,setNewCategory]=useState({service:"",package:""});
  const [newSubcategory,setNewSubcategory]=useState<Record<string,string>>({});
  const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [message,setMessage]=useState("");

  async function run(key:string,action:()=>Promise<unknown>,success:string){setBusy(key);setError("");setMessage("");try{await action();await onChanged();setMessage(success);}catch(value){setError(value instanceof Error?value.message:"Unable to update definitions.");}finally{setBusy("");}}
  async function addCategory(scope:"service"|"package"){const name=newCategory[scope].trim();if(!name)return;await run(`add-${scope}`,()=>taxonomyApi("POST",{scope,level:"category",name}),`${name} category added.`);setNewCategory(current=>({...current,[scope]:""}));}
  async function addSubcategory(scope:"service"|"package",parentId:string){const key=`${scope}-${parentId}`;const name=(newSubcategory[key]||"").trim();if(!name)return;await run(`add-${key}`,()=>taxonomyApi("POST",{scope,level:"subcategory",parentId,name}),`${name} subcategory added.`);setNewSubcategory(current=>({...current,[key]:""}));}
  async function rename(scope:"service"|"package",level:"category"|"subcategory",item:TaxonomyCategory){const name=window.prompt(`Rename ${level}`,item.name)?.trim();if(!name||name===item.name)return;await run(`edit-${item.id}`,()=>taxonomyApi("PATCH",{scope,level,id:item.id,name}),`${level} renamed.`);}
  async function recolor(item:TaxonomyCategory,color:string){await run(`color-${item.id}`,()=>taxonomyApi("PATCH",{scope:"service",level:"category",id:item.id,name:item.name,calendarColor:color}),`${item.name} calendar color saved.`);}
  async function remove(scope:"service"|"package",level:"category"|"subcategory",item:TaxonomyCategory){if(!window.confirm(`Delete ${item.name}? Categories currently used by catalog items cannot be deleted.`))return;await run(`delete-${item.id}`,()=>taxonomyApi("DELETE",{scope,level,id:item.id}),`${item.name} deleted.`);}

  function group(scope:"service"|"package",categories:TaxonomyCategory[],subcategories:TaxonomySubcategory[]){return <section className="taxonomy-group"><header><div><p>{scope.toUpperCase()} DEFINITIONS</p><h3>{scope==="service"?"Service":"Package"} categories</h3></div><form onSubmit={(event)=>{event.preventDefault();void addCategory(scope);}}><input value={newCategory[scope]} onChange={event=>setNewCategory(current=>({...current,[scope]:event.target.value}))} placeholder="New category" required/><button disabled={Boolean(busy)}><i className="fa-solid fa-plus"/> Add</button></form></header><div className="taxonomy-category-list">{categories.map(category=>{const key=`${scope}-${category.id}`;const children=subcategories.filter(item=>item.category_id===category.id);return <article key={category.id}><div className="taxonomy-category-head"><strong>{category.name}</strong><span>{scope==="service"&&<label className="taxonomy-color" title={`${category.name} calendar color`}><input type="color" value={category.calendar_color||"#c65373"} disabled={Boolean(busy)} onChange={event=>void recolor(category,event.target.value)}/></label>}<button type="button" onClick={()=>void rename(scope,"category",category)} disabled={Boolean(busy)} aria-label={`Rename ${category.name}`}><i className="fa-solid fa-pen"/></button><button type="button" className="danger" onClick={()=>void remove(scope,"category",category)} disabled={Boolean(busy)} aria-label={`Delete ${category.name}`}><i className="fa-solid fa-trash-can"/></button></span></div><ul>{children.map(item=><li key={item.id}><span>{item.name}</span><div><button type="button" onClick={()=>void rename(scope,"subcategory",item)} disabled={Boolean(busy)}><i className="fa-solid fa-pen"/> Edit</button><button type="button" className="danger" onClick={()=>void remove(scope,"subcategory",item)} disabled={Boolean(busy)}><i className="fa-solid fa-trash-can"/> Delete</button></div></li>)}</ul><form className="taxonomy-subcategory-add" onSubmit={(event)=>{event.preventDefault();void addSubcategory(scope,category.id);}}><input value={newSubcategory[key]||""} onChange={event=>setNewSubcategory(current=>({...current,[key]:event.target.value}))} placeholder="New subcategory" required/><button disabled={Boolean(busy)}>Add subcategory</button></form></article>})}{!categories.length&&<p className="taxonomy-empty">Add a category to begin.</p>}</div></section>}

  return <section className="catalog-taxonomy-manager"><header><div><p>CATALOG STRUCTURE</p><h2>Categories &amp; subcategories</h2><span>Manage the dropdown choices used when adding or editing services and packages.</span></div><i className="fa-solid fa-layer-group"/></header>{error&&<p className="account-alert error">{error}</p>}{message&&<p className="account-alert success">{message}</p>}<div className="taxonomy-grid">{group("service",serviceCategories,serviceSubcategories)}{group("package",packageCategories,packageSubcategories)}</div></section>;
}
