"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Payment = {
  id: string; appointment_id: string; amount: number | string; currency: string; method: string;
  status: string; paymongo_payment_id: string | null; paid_at: string | null; refunded_at: string | null;
  refund_amount: number | string | null; created_at: string;
  appointments: { reference_no: string; appointment_date: string; appointment_time: string; visit_kind: string; services: { name: string } | { name: string }[] | null } | { reference_no: string; appointment_date: string; appointment_time: string; visit_kind: string; services: { name: string } | { name: string }[] | null }[];
};

const first = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] : value;
const money = (value: number | string) => `PHP ${Number(value).toLocaleString("en-PH", { minimumFractionDigits: 2 })}`;

export default function PatientPaymentsPage({ payingId, onPay, onVerify }: { payingId: string | null; onPay: (id: string) => Promise<void>; onVerify: (id: string) => void }) {
  const [payments, setPayments] = useState<Payment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [filter, setFilter] = useState<"all" | "paid" | "pending">("all");
  useEffect(() => { let active = true; void supabase.auth.getSession().then(({ data }) => fetch("/api/patient-payments", { headers: { Authorization: `Bearer ${data.session?.access_token || ""}` } })).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); if (active) setPayments(result.payments || []); }).catch((value) => active && setError(value instanceof Error ? value.message : "Unable to load payments.")).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);
  const paid = payments.filter((item) => item.status === "paid"); const pending = payments.filter((item) => ["pending", "awaiting_payment"].includes(item.status));
  const shown = payments.filter((item) => filter === "all" || (filter === "paid" ? item.status === "paid" : item.status !== "paid"));
  return <div className="ps-workspace"><section className="ps-hero"><div><p className="dk-welcome-label">Billing center</p><h1>Payments & receipts</h1><p>Review actual transactions, complete pending payments, and keep references for your records.</p></div><i className="fa-solid fa-receipt" /></section><div className="ps-metrics"><article><span>Total transactions</span><strong>{payments.length}</strong></article><article><span>Paid</span><strong>{money(paid.reduce((sum, item) => sum + Number(item.amount), 0))}</strong></article><article><span>Action needed</span><strong>{pending.length}</strong></article></div><section className="ps-panel"><header><div><h2>Transaction history</h2><p>Payments are processed through PayMongo using QR Ph.</p></div><div className="ps-payment-filter">{(["all","paid","pending"] as const).map((value) => <button type="button" className={filter === value ? "active" : ""} key={value} onClick={() => setFilter(value)}>{value}</button>)}</div></header>{error && <p className="ps-alert error">{error}</p>}{loading ? <div className="dk-empty"><i className="fa-solid fa-spinner fa-spin" /><p>Loading payment records…</p></div> : shown.length ? <div className="ps-payment-list">{shown.map((payment) => { const appointment = first(payment.appointments); const service = first(appointment?.services || null); const pendingPayment = ["pending","awaiting_payment"].includes(payment.status); return <article key={payment.id}><div className="ps-payment-icon"><i className={`fa-solid ${payment.status === "paid" ? "fa-check" : payment.status.includes("refund") ? "fa-rotate-left" : "fa-receipt"}`} /></div><div><small>{appointment?.reference_no || "Payment"}</small><h3>{service?.name || "Clinic appointment"}</h3><p>{appointment?.appointment_date} · {appointment?.appointment_time?.slice(0,5)} · {payment.method === "paymongo_qr_ph" ? "QR Ph via PayMongo" : payment.method}</p><span className="ps-transaction-ref">Transaction: {payment.paymongo_payment_id || payment.id}</span></div><div className="ps-payment-amount"><strong>{money(payment.amount)}</strong><span className={`ps-payment-status ${payment.status === "paid" ? "paid" : "pending"}`}>{payment.status.replaceAll("_", " ")}</span><small>{new Date(payment.paid_at || payment.created_at).toLocaleDateString("en-PH", { year: "numeric", month: "short", day: "numeric" })}</small></div>{pendingPayment && <div className="ps-payment-actions"><button disabled={payingId === payment.appointment_id} onClick={() => void onPay(payment.appointment_id)}>{payingId === payment.appointment_id ? "Opening…" : "Pay now"}</button><button className="secondary" onClick={() => onVerify(payment.appointment_id)}>Verify</button></div>}</article>; })}</div> : <div className="dk-empty"><div className="dk-empty-icon"><i className="fa-solid fa-receipt" /></div><h3>No transactions here</h3><p>Payment records matching this filter will appear here.</p></div>}</section></div>;
}
