"use client";
import { useEffect,useMemo,useState } from "react";
import { supabase } from "@/lib/supabase";
import type { PatientRecord } from "@/lib/patients";
import type { BookingSlot } from "@/lib/bookingAvailability";
type Category={id:string;name:string;slug:string};
type Service={id:string;category_id:string;subcategory:string;name:string;slug:string;duration_mins:number|null};
type BookingType="consultation"|"procedure";
const today=()=>{const value=new Date();return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`};

export default function StaffAppointmentModal({patient,onClose,onCreated}:{patient:PatientRecord;onClose:()=>void;onCreated:()=>void|Promise<void>}){
 const[categories,setCategories]=useState<Category[]>([]),[services,setServices]=useState<Service[]>([]),[bookingType,setBookingType]=useState<BookingType>("consultation"),[categoryId,setCategoryId]=useState(""),[serviceSlug,setServiceSlug]=useState(""),[date,setDate]=useState(today),[time,setTime]=useState(""),[slots,setSlots]=useState<BookingSlot[]>([]),[hours,setHours]=useState(""),[availabilityMessage,setAvailabilityMessage]=useState(""),[loadingSlots,setLoadingSlots]=useState(true),[notes,setNotes]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const chooseType=(type:BookingType,allCategories=categories,allServices=services)=>{const category=allCategories.find(item=>type==="consultation"?item.slug==="consultations":item.slug!=="consultations");setBookingType(type);setCategoryId(category?.id||"");setServiceSlug(allServices.find(item=>item.category_id===category?.id)?.slug||"");};
 useEffect(()=>{void fetch("/api/booking-catalog").then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);const nextCategories:Category[]=result.categories||[],nextServices:Service[]=result.services||[],category=nextCategories.find(item=>item.slug==="consultations");setCategories(nextCategories);setServices(nextServices);setCategoryId(category?.id||"");setServiceSlug(nextServices.find(item=>item.category_id===category?.id)?.slug||"")}).catch(value=>setError(value instanceof Error?value.message:"Unable to load procedures."))},[]);
 useEffect(()=>{const controller=new AbortController();void fetch(`/api/booking-availability?date=${date}`,{signal:controller.signal,cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);setSlots(result.slots||[]);setHours(result.hours||"");setAvailabilityMessage(result.reason||"")}).catch(value=>{if(!(value instanceof DOMException&&value.name==="AbortError")){setSlots([]);setAvailabilityMessage(value instanceof Error?value.message:"Unable to load available times.")}}).finally(()=>{if(!controller.signal.aborted)setLoadingSlots(false)});return()=>controller.abort()},[date]);
 const visibleCategories=useMemo(()=>categories.filter(item=>bookingType==="consultation"?item.slug==="consultations":item.slug!=="consultations"),[categories,bookingType]);
 const procedures=useMemo(()=>services.filter(item=>item.category_id===categoryId),[services,categoryId]);
 const selectedService=services.find(item=>item.slug===serviceSlug);
 async function submit(event:React.FormEvent){event.preventDefault();if(!time){setError("Choose an available time slot.");return}setSaving(true);setError("");try{const{data}=await supabase.auth.getSession();if(!data.session)throw new Error("Your session expired. Please sign in again.");const response=await fetch("/api/appointments",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({clientId:patient.id,serviceSlug,appointmentDate:date,appointmentTime:`${time}:00`,notes,consentAcknowledged:true})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to create appointment.");await onCreated();onClose()}catch(value){setError(value instanceof Error?value.message:"Unable to create appointment.")}finally{setSaving(false)}}
 return <div className="staff-booking-overlay" onClick={event=>event.target===event.currentTarget&&!saving&&onClose()}><section className="staff-booking-modal" role="dialog" aria-modal="true" aria-labelledby="staff-booking-title"><header><span className="staff-booking-icon"><i className="fa-solid fa-calendar-plus"/></span><div><small>BOOK AN APPOINTMENT</small><h2 id="staff-booking-title">{patient.fullName}</h2><p>{patient.patientNo} · Clinic patient · Walk-in / phone booking</p></div><button type="button" onClick={onClose} aria-label="Close"><i className="fa-solid fa-xmark"/></button></header><form onSubmit={submit}><div className="staff-booking-content">
   <div className="staff-booking-intro"><span><i className="fa-solid fa-kit-medical"/></span><div><h3>Choose Your Treatment</h3><p>Select the service you&apos;d like to book with Dr. Kharyl.</p></div></div>
   <fieldset><legend>VISIT &amp; TREATMENT</legend><div className="staff-booking-types"><button type="button" className={bookingType==="consultation"?"active consultation":""} onClick={()=>chooseType("consultation")}><i className="fa-solid fa-user-doctor"/><span><small>ASSESSMENT ONLY</small><strong>Consultation</strong><em>Meet Dr. Kharyl for evaluation and a personalized treatment plan.</em></span></button><button type="button" className={bookingType==="procedure"?"active procedure":""} onClick={()=>chooseType("procedure")}><i className="fa-solid fa-syringe"/><span><small>BOOK PROCEDURES</small><strong>Medical Treatment</strong><em>Select a treatment to add to this appointment.</em></span></button></div></fieldset>
   <div className="staff-booking-grid"><label><span>TREATMENT CATEGORY</span><select value={categoryId} onChange={event=>{const id=event.target.value;setCategoryId(id);setServiceSlug(services.find(item=>item.category_id===id)?.slug||"")}} required>{visibleCategories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>CONSULTATION / TREATMENT</span><select value={serviceSlug} onChange={event=>setServiceSlug(event.target.value)} required><option value="">Choose a treatment</option>{procedures.map(item=><option key={item.id} value={item.slug}>{item.name}{item.subcategory?` — ${item.subcategory}`:""}</option>)}</select></label></div>
   <label className="staff-booking-date"><span><i className="fa-regular fa-calendar"/> DATE &amp; TIME</span><input type="date" min={today()} value={date} onChange={event=>{setLoadingSlots(true);setTime("");setDate(event.target.value)}} required/></label>
   <div className="staff-booking-hours"><i className="fa-solid fa-building"/><span>The Klinique{hours?` · ${hours}`:""}</span></div>
   <fieldset><legend><i className="fa-regular fa-clock"/> AVAILABLE TIME SLOTS{selectedService?.duration_mins?` · ${selectedService.duration_mins} MIN`:""}</legend>{loadingSlots?<p className="staff-booking-status"><i className="fa-solid fa-spinner fa-spin"/> Loading available times...</p>:availabilityMessage?<p className="staff-booking-status error">{availabilityMessage}</p>:<div className="staff-booking-slots">{slots.map(slot=><button type="button" key={slot.time} disabled={slot.status!=="available"} className={time===slot.time?"selected":""} onClick={()=>setTime(slot.time)}><strong>{slot.label}</strong><small>{slot.status==="available"?"Available":slot.status==="past"?"Past":"Booked"}</small></button>)}</div>}</fieldset>
   <label className="staff-booking-notes"><span><i className="fa-solid fa-clipboard"/> TREATMENT CONCERN / NOTES</span><textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder={bookingType==="procedure"?"Target areas, treatment goals, allergies, or special instructions...":"Reason for consultation or follow-up notes..."}/></label>
   {error&&<p className="bk-form-error">{error}</p>}
 </div><footer><button type="button" onClick={onClose}>Cancel</button><button className="confirm" disabled={saving||!serviceSlug||!time}><i className={`fa-solid ${saving?"fa-spinner fa-spin":"fa-calendar-check"}`}/> {saving?"Saving appointment...":"Confirm Appointment"}</button></footer></form></section></div>
}
