"use client";
import { useEffect,useMemo,useState } from "react";
import { supabase } from "@/lib/supabase";
import type { PatientRecord } from "@/lib/patients";
import type { BookingSlot } from "@/lib/bookingAvailability";
type Category={id:string;name:string;slug:string};
type Service={id:string;category_id:string;subcategory:string;name:string;slug:string;description:string|null;price:number;duration_mins:number|null};
type Product={id:string;name:string;description:string|null;price:number;category:string;subcategory:string};
type BookingType="consultation"|"procedure"|"package";
const PACKAGE_SLUG="glow-plans-package-booking";
const today=()=>{const value=new Date();return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`};

export default function StaffAppointmentModal({patient,onClose,onCreated}:{patient:PatientRecord;onClose:()=>void;onCreated:()=>void|Promise<void>}){
 const[categories,setCategories]=useState<Category[]>([]),[services,setServices]=useState<Service[]>([]),[products,setProducts]=useState<Product[]>([]);
 const[bookingType,setBookingType]=useState<BookingType>("consultation"),[categoryId,setCategoryId]=useState(""),[serviceSlug,setServiceSlug]=useState("");
 const[treatmentIds,setTreatmentIds]=useState<string[]>([]),[productIds,setProductIds]=useState<string[]>([]);
 const[date,setDate]=useState(today),[time,setTime]=useState(""),[slots,setSlots]=useState<BookingSlot[]>([]),[hours,setHours]=useState(""),[availabilityMessage,setAvailabilityMessage]=useState(""),[loadingSlots,setLoadingSlots]=useState(true),[notes,setNotes]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const chooseType=(type:BookingType,allCategories=categories,allServices=services)=>{setBookingType(type);setTreatmentIds([]);setProductIds([]);if(type==="package"){const item=allServices.find(service=>service.slug===PACKAGE_SLUG);setCategoryId(item?.category_id||"");setServiceSlug(item?.slug||"");return}const category=allCategories.find(item=>type==="consultation"?item.slug==="consultations":!["consultations","package-bookings"].includes(item.slug));setCategoryId(category?.id||"");setServiceSlug(allServices.find(item=>item.category_id===category?.id&&item.slug!==PACKAGE_SLUG)?.slug||"")};
 useEffect(()=>{void fetch("/api/booking-catalog").then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);const nextCategories:Category[]=result.categories||[],nextServices:Service[]=result.services||[],category=nextCategories.find(item=>item.slug==="consultations");setCategories(nextCategories);setServices(nextServices);setProducts(result.products||[]);setCategoryId(category?.id||"");setServiceSlug(nextServices.find(item=>item.category_id===category?.id)?.slug||"")}).catch(value=>setError(value instanceof Error?value.message:"Unable to load procedures."))},[]);
 useEffect(()=>{const controller=new AbortController();void fetch(`/api/booking-availability?date=${date}`,{signal:controller.signal,cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);setSlots(result.slots||[]);setHours(result.hours||"");setAvailabilityMessage(result.reason||"")}).catch(value=>{if(!(value instanceof DOMException&&value.name==="AbortError")){setSlots([]);setAvailabilityMessage(value instanceof Error?value.message:"Unable to load available times.")}}).finally(()=>{if(!controller.signal.aborted)setLoadingSlots(false)});return()=>controller.abort()},[date]);
 const visibleCategories=useMemo(()=>categories.filter(item=>bookingType==="consultation"?item.slug==="consultations":!["consultations","package-bookings"].includes(item.slug)),[categories,bookingType]);
 const procedures=useMemo(()=>services.filter(item=>item.category_id===categoryId&&item.slug!==PACKAGE_SLUG),[services,categoryId]);
 const selectedService=services.find(item=>item.slug===serviceSlug);
 const treatments=services.filter(item=>item.slug!==PACKAGE_SLUG&&categories.find(category=>category.id===item.category_id)?.slug!=="consultations");
 const groups=products.reduce<Record<string,Product[]>>((all,product)=>{const key=product.subcategory&&product.subcategory!=="General"?`${product.category} / ${product.subcategory}`:product.category;(all[key]||=[]).push(product);return all},{});
 const toggleTreatment=(id:string)=>setTreatmentIds(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
 const toggleProduct=(id:string)=>setProductIds(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
 async function submit(event:React.FormEvent){event.preventDefault();if(!time){setError("Choose an available time slot.");return}if(bookingType==="package"&&!productIds.length){setError("Choose at least one package.");return}setSaving(true);setError("");try{const{data}=await supabase.auth.getSession();if(!data.session)throw new Error("Your session expired. Please sign in again.");const response=await fetch("/api/appointments",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({clientId:patient.id,serviceSlug,appointmentDate:date,appointmentTime:`${time}:00`,treatmentIds:bookingType==="procedure"?treatmentIds:[],productIds:bookingType==="package"?productIds:[],notes,consentAcknowledged:true})}),result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to create appointment.");await onCreated();onClose()}catch(value){setError(value instanceof Error?value.message:"Unable to create appointment.")}finally{setSaving(false)}}
 return <div className="staff-booking-overlay" onClick={event=>event.target===event.currentTarget&&!saving&&onClose()}><section className="staff-booking-modal" role="dialog" aria-modal="true" aria-labelledby="staff-booking-title"><header><span className="staff-booking-icon"><i className="fa-solid fa-calendar-plus"/></span><div><small>BOOK AN APPOINTMENT</small><h2 id="staff-booking-title">{patient.fullName}</h2><p>{patient.patientNo} · Clinic patient · Walk-in / phone booking</p></div><button type="button" onClick={onClose} aria-label="Close"><i className="fa-solid fa-xmark"/></button></header><form onSubmit={submit}><div className="staff-booking-content">
  <div className="staff-booking-intro"><span><i className="fa-solid fa-kit-medical"/></span><div><h3>Choose Your Treatment</h3><p>Select services or packages using the same options available in online booking.</p></div></div>
  <fieldset><legend>VISIT &amp; TREATMENT</legend><div className="staff-booking-types"><button type="button" className={bookingType==="consultation"?"active consultation":""} onClick={()=>chooseType("consultation")}><i className="fa-solid fa-user-doctor"/><span><small>ASSESSMENT ONLY</small><strong>Consultation</strong><em>Evaluation and a personalized treatment plan.</em></span></button><button type="button" className={bookingType==="procedure"?"active procedure":""} onClick={()=>chooseType("procedure")}><i className="fa-solid fa-syringe"/><span><small>BOOK PROCEDURES</small><strong>Medical Treatment</strong><em>Select one or more treatments.</em></span></button><button type="button" className={bookingType==="package"?"active package":""} disabled={!products.length} onClick={()=>chooseType("package")}><i className="fa-solid fa-gift"/><span><small>GLOW PLANS</small><strong>Package</strong><em>Choose one or more clinic packages.</em></span></button></div></fieldset>
  {bookingType!=="package"&&<div className="staff-booking-grid"><label><span>TREATMENT CATEGORY</span><select value={categoryId} onChange={event=>{const id=event.target.value;setCategoryId(id);setServiceSlug(services.find(item=>item.category_id===id&&item.slug!==PACKAGE_SLUG)?.slug||"")}} required>{visibleCategories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>CONSULTATION / TREATMENT</span><select value={serviceSlug} onChange={event=>setServiceSlug(event.target.value)} required><option value="">Choose a treatment</option>{procedures.map(item=><option key={item.id} value={item.slug}>{item.name}{item.subcategory?` — ${item.subcategory}`:""}</option>)}</select></label></div>}
  {bookingType==="procedure"&&<fieldset className="staff-booking-catalog"><legend><i className="fa-solid fa-list-check"/> ADD MORE TREATMENTS</legend><div className="staff-booking-options">{treatments.filter(item=>item.slug!==serviceSlug).map(item=><button type="button" key={item.id} className={treatmentIds.includes(item.id)?"selected":""} onClick={()=>toggleTreatment(item.id)}><span><strong>{item.name}</strong><small>{item.subcategory||"Treatment"} · ₱{Number(item.price).toLocaleString()}</small></span><i className={`fa-solid ${treatmentIds.includes(item.id)?"fa-check":"fa-plus"}`}/></button>)}</div></fieldset>}
  {bookingType==="package"&&<fieldset className="staff-booking-catalog"><legend><i className="fa-solid fa-gift"/> PACKAGES · {productIds.length} SELECTED</legend><div className="staff-package-groups">{Object.entries(groups).map(([label,items])=><section key={label}><h4>{label}</h4><div className="staff-booking-options">{items.map(item=><button type="button" key={item.id} className={productIds.includes(item.id)?"selected":""} onClick={()=>toggleProduct(item.id)}><span><strong>{item.name}</strong><small>{item.description||"Glow Plan"} · ₱{Number(item.price).toLocaleString()}</small></span><i className={`fa-solid ${productIds.includes(item.id)?"fa-check":"fa-plus"}`}/></button>)}</div></section>)}</div></fieldset>}
  <label className="staff-booking-date"><span><i className="fa-regular fa-calendar"/> DATE &amp; TIME</span><input type="date" min={today()} value={date} onChange={event=>{setLoadingSlots(true);setTime("");setDate(event.target.value)}} required/></label>
  <div className="staff-booking-hours"><i className="fa-solid fa-building"/><span>The Klinique{hours?` · ${hours}`:""}</span></div>
  <fieldset><legend><i className="fa-regular fa-clock"/> AVAILABLE TIME SLOTS{selectedService?.duration_mins?` · ${selectedService.duration_mins} MIN`:""}</legend>{loadingSlots?<p className="staff-booking-status"><i className="fa-solid fa-spinner fa-spin"/> Loading available times...</p>:availabilityMessage?<p className="staff-booking-status error">{availabilityMessage}</p>:<div className="staff-booking-slots">{slots.map(slot=><button type="button" key={slot.time} disabled={slot.status!=="available"} className={time===slot.time?"selected":""} onClick={()=>setTime(slot.time)}><strong>{slot.label}</strong><small>{slot.status==="available"?"Available":slot.status==="past"?"Past":"Booked"}</small></button>)}</div>}</fieldset>
  <label className="staff-booking-notes"><span><i className="fa-solid fa-clipboard"/> TREATMENT CONCERN / NOTES</span><textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder={bookingType==="consultation"?"Reason for consultation or follow-up notes...":"Target areas, treatment goals, allergies, or special instructions..."}/></label>
  {error&&<p className="bk-form-error">{error}</p>}
 </div><footer><button type="button" onClick={onClose}>Cancel</button><button className="confirm" disabled={saving||!serviceSlug||!time||(bookingType==="package"&&!productIds.length)}><i className={`fa-solid ${saving?"fa-spinner fa-spin":"fa-calendar-check"}`}/> {saving?"Saving appointment...":"Confirm Appointment"}</button></footer></form></section></div>
}
