"use client";
import { useEffect,useMemo,useState } from "react";
import { supabase } from "@/lib/supabase";

type Field={key:string;label:string;type:string;required:boolean};
type Protocol={consent_title:string;consent_version:string;consent_text:string|null;anesthesia_requirement:string;allowed_anesthesia:string[];procedure_fields:Field[];postcare_instructions:string|null;default_follow_up_days:number|null};
type Treatment={appointmentId:string;referenceNo:string;date:string;time:string;appointmentStatus:string;patient:string;email:string;phone:string;service:string;case:Record<string,unknown>|null;protocol:Protocol|null};
type Form={consentGiven:boolean;consentSignatureName:string;anesthesiaType:string;anesthesiaProduct:string;anesthesiaAmount:string;anesthesiaNotes:string;procedureDetails:Record<string,string>;procedureNotes:string;postcareInstructions:string;postcareGiven:boolean};
const blank:Form={consentGiven:false,consentSignatureName:"",anesthesiaType:"none",anesthesiaProduct:"",anesthesiaAmount:"",anesthesiaNotes:"",procedureDetails:{},procedureNotes:"",postcareInstructions:"",postcareGiven:false};
const steps=["Consent","Anesthesia","Procedure","Post-Care"];
async function authHeaders(){const {data}=await supabase.auth.getSession();return {"Content-Type":"application/json",Authorization:`Bearer ${data.session?.access_token||""}`};}
function stringValue(value:unknown){return typeof value==="string"?value:"";} function boolValue(value:unknown){return value===true;}

export default function TreatmentWorkspace({onCompleted,initialAppointmentId=null}:{onCompleted:()=>Promise<void>;initialAppointmentId?:string|null}){
 const [items,setItems]=useState<Treatment[]>([]),[selectedId,setSelectedId]=useState<string|null>(initialAppointmentId),[step,setStep]=useState(1),[form,setForm]=useState<Form>(blank),[query,setQuery]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const selected=items.find((item)=>item.appointmentId===selectedId)||items[0]||null;
 const visible=useMemo(()=>items.filter((item)=>!query.trim()||[item.patient,item.service,item.referenceNo].some((value)=>value.toLowerCase().includes(query.toLowerCase()))),[items,query]);
 useEffect(()=>{void authHeaders().then((headers)=>fetch("/api/treatments",{headers})).then((r)=>r.json()).then((result)=>setItems(result.cases||[])).catch(()=>setError("Unable to load treatments."));},[]);
 useEffect(()=>{if(initialAppointmentId)queueMicrotask(()=>setSelectedId(initialAppointmentId));},[initialAppointmentId]);
 useEffect(()=>{if(!selected)return;const value=selected.case||{};queueMicrotask(()=>{setStep(Math.min(4,Number(value.current_step)||1));setForm({consentGiven:boolValue(value.consent_given),consentSignatureName:stringValue(value.consent_signature_name),anesthesiaType:stringValue(value.anesthesia_type)||"none",anesthesiaProduct:stringValue(value.anesthesia_product),anesthesiaAmount:stringValue(value.anesthesia_amount),anesthesiaNotes:stringValue(value.anesthesia_notes),procedureDetails:(value.procedure_details&&typeof value.procedure_details==="object"?value.procedure_details:{}) as Record<string,string>,procedureNotes:stringValue(value.procedure_notes),postcareInstructions:stringValue(value.postcare_instructions)||selected.protocol?.postcare_instructions||"",postcareGiven:boolValue(value.postcare_given)});});},[selected]);
 async function save(nextStep=step,status:"in_progress"|"completed"="in_progress"){if(!selected)return false;setSaving(true);setError("");try{const protocol=selected.protocol;const response=await fetch("/api/treatments",{method:"PATCH",headers:await authHeaders(),body:JSON.stringify({appointmentId:selected.appointmentId,currentStep:nextStep,status,...form,consentVersion:protocol?.consent_version||"1.0",consentTextSnapshot:protocol?.consent_text||""})});const result=await response.json();if(!response.ok)throw new Error(result.error);setItems((values)=>values.map((item)=>item.appointmentId===selected.appointmentId?{...item,case:result.case,appointmentStatus:status==="completed"?"completed":item.appointmentStatus}:item));if(status==="completed")await onCompleted();return true;}catch(value){setError(value instanceof Error?value.message:"Unable to save treatment.");return false;}finally{setSaving(false);}}
 async function next(){if(step===1&&(!form.consentGiven||!form.consentSignatureName.trim())){setError("Patient acknowledgment and signature name are required.");return;}if(step===2&&selected?.protocol?.anesthesia_requirement==="required"&&form.anesthesiaType==="none"){setError("This treatment requires an anesthesia record.");return;}if(step===3&&fields.some((field)=>field.required&&!form.procedureDetails[field.key]?.trim())){setError("Complete all required procedure fields.");return;}const nextStep=Math.min(4,step+1);if(await save(nextStep))setStep(nextStep);}
 const fields=selected?.protocol?.procedure_fields||[{key:"treatment_area",label:"Treatment area",type:"text",required:true},{key:"product_device",label:"Product or device",type:"text",required:false},{key:"settings_dose",label:"Settings or dose",type:"text",required:false},{key:"lot_number",label:"Lot / batch number",type:"text",required:false}];
 return <div className="tw-workspace"><section className="pr-hero"><div><p className="dk-welcome-label">Treatments / Medical Procedures</p><h1>Treatment Workspace</h1><span>One safe six-stage workflow, configured for each The Klinique treatment.</span></div></section><div className="tw-layout"><aside><header><h2>Procedure queue</h2><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search patient or treatment..."/></header><div>{visible.map((item)=><button type="button" className={selected?.appointmentId===item.appointmentId?"active":""} onClick={()=>setSelectedId(item.appointmentId)} key={item.appointmentId}><strong>{item.patient}</strong><span>{item.date} · {item.time}</span><small>{item.service}</small></button>)}</div></aside><main>{selected?<><header><div><span className="ma-visit-pill">Medical procedure</span><small>{selected.referenceNo}</small><h2>{selected.patient}</h2><p>{selected.service} · {selected.date} at {selected.time}</p></div><em>{selected.case?.status==="completed"?"Completed":"In progress"}</em></header><nav className="tw-steps">{steps.map((label,index)=><button type="button" key={label} className={step===index+1?"active":step>index+1?"done":""} onClick={()=>setStep(index+1)}><b>{step>index+1?<i className="fa-solid fa-check"/>:index+1}</b><span>{label}</span></button>)}</nav><section className="tw-form">
 {step===1&&<><h3>{selected.protocol?.consent_title||`${selected.service} Consent`}</h3><div className="tw-consent">{selected.protocol?.consent_text||"The procedure, benefits, alternatives, material risks, and aftercare have been explained. The patient had an opportunity to ask questions and voluntarily consents to treatment."}</div><label><span>Patient signature / acknowledgment name</span><input value={form.consentSignatureName} onChange={(e)=>setForm({...form,consentSignatureName:e.target.value})}/></label><label className="tw-check"><input type="checkbox" checked={form.consentGiven} onChange={(e)=>setForm({...form,consentGiven:e.target.checked})}/><span>The patient reviewed and accepted this consent in the presence of clinic staff.</span></label></>}
 {step===2&&<><h3>Pre-treatment anesthesia</h3><p>Record what was actually administered. Select None when anesthesia is not required.</p><label><span>Type</span><select value={form.anesthesiaType} onChange={(e)=>setForm({...form,anesthesiaType:e.target.value})}>{(selected.protocol?.allowed_anesthesia||["none","topical","local"]).map((value)=><option key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</select></label><div className="tw-grid"><label><span>Product</span><input value={form.anesthesiaProduct} onChange={(e)=>setForm({...form,anesthesiaProduct:e.target.value})}/></label><label><span>Amount / concentration</span><input value={form.anesthesiaAmount} onChange={(e)=>setForm({...form,anesthesiaAmount:e.target.value})}/></label></div><label><span>Notes</span><textarea value={form.anesthesiaNotes} onChange={(e)=>setForm({...form,anesthesiaNotes:e.target.value})}/></label></>}
 {step===3&&<><h3>{selected.service} procedure record</h3><div className="tw-grid">{fields.map((field)=><label key={field.key}><span>{field.label}{field.required?" *":""}</span><input required={field.required} value={form.procedureDetails[field.key]||""} onChange={(e)=>setForm({...form,procedureDetails:{...form.procedureDetails,[field.key]:e.target.value}})}/></label>)}</div><label><span>Procedure notes</span><textarea value={form.procedureNotes} onChange={(e)=>setForm({...form,procedureNotes:e.target.value})}/></label></>}
 {step===4&&<><h3>Post-care instructions</h3><label><span>Instructions provided</span><textarea value={form.postcareInstructions} onChange={(e)=>setForm({...form,postcareInstructions:e.target.value})}/></label><label className="tw-check"><input type="checkbox" checked={form.postcareGiven} onChange={(e)=>setForm({...form,postcareGiven:e.target.checked})}/><span>Post-care instructions were explained and given to the patient.</span></label></>}
 {error&&<p className="bk-form-error">{error}</p>}<footer><button type="button" className="dk-btn dk-btn-outline" disabled={saving||step===1} onClick={()=>setStep(step-1)}>Previous</button><button type="button" className="dk-btn dk-btn-outline" disabled={saving} onClick={()=>save(step)}>Save draft</button>{step<4?<button type="button" className="dk-btn dk-btn-pink" disabled={saving} onClick={next}>Save &amp; continue</button>:<button type="button" className="dk-btn dk-btn-pink" disabled={saving||!form.postcareGiven} onClick={()=>save(4,"completed")}><i className="fa-solid fa-check-double"/> Finalize treatment</button>}</footer></section></>:<div className="pr-loading"><i className="fa-solid fa-syringe"/>No confirmed treatment appointments.</div>}</main></div></div>;
}
