"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { normalizeFacebookPostUrl, normalizeLandingSocialContent } from "@/lib/landing-social";

export type LandingMedia = { url: string; type: "image" | "video"; alt: string };
export type LandingFaq = { question:string; answer:string };
export type LandingSocialPost = { title:string; url:string; platform:"facebook"|"instagram" };
export type LandingServiceCard = { name:string; tagline:string; image:string; alt:string };
type ContentTab = "home"|"about"|"services"|"doctor"|"social"|"gallery"|"faq"|"contact";
export type LandingContent = { heroEyebrow:string;heroTitle:string;heroSubtitle:string;heroDescription:string;doctorEyebrow:string;doctorName:string;doctorTitle:string;doctorBio:string;doctorPhoto:string;socialHeading:string;socialPostUrl:string;facebookPageUrl:string;instagramUrl:string;aboutEyebrow:string;aboutTitle:string;aboutBody:string;aboutImage:string;servicesEyebrow:string;servicesTitle:string;galleryEyebrow:string;galleryTitle:string;galleryDescription:string;galleryBadge:string;quoteText:string;quoteSubtitle:string;contactEyebrow:string;contactTitle:string;contactBody:string;phone:string;email:string;address:string;clinicHours:string;footerTagline:string;heroMedia:LandingMedia[];galleryMedia:LandingMedia[];faqs:LandingFaq[];socialPosts:LandingSocialPost[];serviceShowcase:LandingServiceCard[] };
const empty: LandingContent = { heroEyebrow:"",heroTitle:"",heroSubtitle:"",heroDescription:"",doctorEyebrow:"",doctorName:"",doctorTitle:"",doctorBio:"",doctorPhoto:"",socialHeading:"",socialPostUrl:"",facebookPageUrl:"",instagramUrl:"",aboutEyebrow:"",aboutTitle:"",aboutBody:"",aboutImage:"",servicesEyebrow:"",servicesTitle:"",galleryEyebrow:"",galleryTitle:"",galleryDescription:"",galleryBadge:"",quoteText:"",quoteSubtitle:"",contactEyebrow:"",contactTitle:"",contactBody:"",phone:"",email:"",address:"",clinicHours:"",footerTagline:"",heroMedia:[],galleryMedia:[],faqs:[],socialPosts:[],serviceShowcase:[] };

async function token() { const { data } = await supabase.auth.getSession(); if (!data.session) throw new Error("Your session expired."); return data.session.access_token; }
export default function WebsiteContentManager() {
  const [content,setContent]=useState<LandingContent>(empty); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const [tab,setTab]=useState<ContentTab>("home");
  useEffect(()=>{ void fetch("/api/landing-content").then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error);setContent(normalizeLandingSocialContent({...empty,...x.content,heroMedia:x.content?.heroMedia||[],galleryMedia:x.content?.galleryMedia||[],faqs:x.content?.faqs||[],socialPosts:x.content?.socialPosts||[],serviceShowcase:x.content?.serviceShowcase||[]}));}).catch(e=>setError(e.message)).finally(()=>setLoading(false)); },[]);
  const field=(key:keyof LandingContent,value:string)=>setContent(current=>({...current,[key]:value}));
  async function save(){setSaving(true);setError("");setMessage("");try{const normalized=normalizeLandingSocialContent(content);const response=await fetch("/api/landing-content",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await token()}`},body:JSON.stringify({content:normalized})});const result=await response.json();if(!response.ok)throw new Error(result.error);setContent({...empty,...result.content});setMessage("Landing-page content published.");}catch(e){setError(e instanceof Error?e.message:"Unable to save.");}finally{setSaving(false);}}
  async function upload(file:File,target:"hero"|"gallery"|"doctor"|"about"|"service",serviceIndex?:number){if(target==="hero"&&content.heroMedia.length>=5)return setError("The hero carousel supports up to five media items.");setUploading(target==="service"?`service-${serviceIndex}`:target);setError("");try{const form=new FormData();form.append("file",file);const response=await fetch("/api/landing-content",{method:"POST",headers:{Authorization:`Bearer ${await token()}`},body:form});const media=await response.json();if(!response.ok)throw new Error(media.error);setContent(current=>target==="doctor"?{...current,doctorPhoto:media.url}:target==="about"?{...current,aboutImage:media.url}:target==="hero"?{...current,heroMedia:[...current.heroMedia,media]}:target==="service"&&serviceIndex!==undefined?{...current,serviceShowcase:current.serviceShowcase.map((item,index)=>index===serviceIndex?{...item,image:media.url,alt:item.alt||item.name}:item)}:{...current,galleryMedia:[...current.galleryMedia,media]});setMessage("Media uploaded. Click Publish changes to make it live.");}catch(e){setError(e instanceof Error?e.message:"Upload failed.");}finally{setUploading("");}}
  const changeMedia=(target:"hero"|"gallery",action:number|{from:number;to:number})=>setContent(current=>{const key=target==="hero"?"heroMedia":"galleryMedia";const items=[...current[key]];if(typeof action==="number")items.splice(action,1);else{const [moved]=items.splice(action.from,1);items.splice(action.to,0,moved);}return{...current,[key]:items};});
  const remove=changeMedia;
  if(loading)return <div className="staff-settings__loading"><i className="fa-solid fa-spinner fa-spin"/> Loading website content...</div>;
  const tabs:{key:ContentTab;label:string;description:string;icon:string}[]=[{key:"home",label:"Home",description:"Hero carousel",icon:"fa-house"},{key:"about",label:"About",description:"Clinic introduction",icon:"fa-spa"},{key:"services",label:"Services",description:"Cards, images, and copy",icon:"fa-syringe"},{key:"doctor",label:"Doctor",description:"Dr. Kharyl profile",icon:"fa-user-doctor"},{key:"social",label:"Social",description:"Social media posts",icon:"fa-share-nodes"},{key:"gallery",label:"Gallery",description:"Moving results board",icon:"fa-images"},{key:"faq",label:"FAQ",description:"Questions and answers",icon:"fa-circle-question"},{key:"contact",label:"Contact & Footer",description:"Details and footer",icon:"fa-address-card"}];
  return <div className={`website-content-manager tab-${tab}`}><header><div><p>WEBSITE CONTENT</p><h2>Landing-page editor</h2><span>Choose a section below, edit its content, then publish your changes.</span><a className="website-preview-link" href="/" target="_blank">Preview landing page <i className="fa-solid fa-arrow-up-right-from-square"/></a></div><button onClick={()=>void save()} disabled={saving}>{saving?"Publishing...":"Publish changes"}</button></header>{error&&<p className="account-alert error">{error}</p>}{message&&<p className="account-alert success">{message}</p>}<nav className="website-content-tabs" aria-label="Landing page sections">{tabs.map(item=><button type="button" key={item.key} className={tab===item.key?"active":""} onClick={()=>setTab(item.key)}><i className={`fa-solid ${item.icon}`}/><span><strong>{item.label}</strong><small>{item.description}</small></span></button>)}</nav>
    <section><h3>Hero carousel</h3><p>Upload up to five images, GIFs, or videos.</p><div className="website-copy-grid"><label>Headline · cursive accent<input className="website-cursive-preview" value={content.heroTitle} onChange={e=>field("heroTitle",e.target.value)}/></label><label>Eyebrow<input value={content.heroEyebrow} onChange={e=>field("heroEyebrow",e.target.value)}/></label><label>Subtitle<input value={content.heroSubtitle} onChange={e=>field("heroSubtitle",e.target.value)}/></label><label className="wide">Description<textarea value={content.heroDescription} onChange={e=>field("heroDescription",e.target.value)}/></label></div><label className="website-upload"><i className="fa-solid fa-cloud-arrow-up"/><span>{uploading==="hero"?"Uploading...":"Add hero media"}</span><input type="file" accept="image/*,video/mp4,video/webm" disabled={Boolean(uploading)||content.heroMedia.length>=5} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0],"hero")}/></label><MediaList items={content.heroMedia} onRemove={i=>remove("hero",i)}/></section>
    <section><h3>About section</h3><div className="website-copy-grid"><label>Section label<input value={content.aboutEyebrow} onChange={e=>field("aboutEyebrow",e.target.value)}/></label><label>Heading<input value={content.aboutTitle} onChange={e=>field("aboutTitle",e.target.value)}/></label><label className="wide">Description<textarea value={content.aboutBody} onChange={e=>field("aboutBody",e.target.value)}/></label></div>{content.aboutImage&&<div className="website-current-image"><span>Current about image</span><img src={content.aboutImage} alt="Current About section"/></div>}<label className="website-upload"><i className="fa-solid fa-image"/><span>{uploading==="about"?"Uploading...":"Replace about photo"}</span><input type="file" accept="image/*" disabled={Boolean(uploading)} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0],"about")}/></label></section>
    <section><h3>Services showcase</h3><div className="website-copy-grid"><label>Services label<input value={content.servicesEyebrow} onChange={e=>field("servicesEyebrow",e.target.value)}/></label><label>Services heading<input value={content.servicesTitle} onChange={e=>field("servicesTitle",e.target.value)}/></label><label>Quote banner<input value={content.quoteText} onChange={e=>field("quoteText",e.target.value)}/></label><label>Quote subtitle<input value={content.quoteSubtitle} onChange={e=>field("quoteSubtitle",e.target.value)}/></label></div><div className="website-service-editor">{content.serviceShowcase.map((service,index)=><article key={index}><div className="website-service-image">{service.image?<img src={service.image} alt={service.alt||service.name}/>:<i className="fa-solid fa-image"/>}<label><i className="fa-solid fa-camera"/> {uploading===`service-${index}`?"Uploading...":"Change image"}<input type="file" accept="image/*" disabled={Boolean(uploading)} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0],"service",index)}/></label></div><div><label>Service name / type<input value={service.name} onChange={e=>setContent(current=>({...current,serviceShowcase:current.serviceShowcase.map((item,i)=>i===index?{...item,name:e.target.value,alt:item.alt||e.target.value}:item)}))}/></label><label>Tagline<input value={service.tagline} onChange={e=>setContent(current=>({...current,serviceShowcase:current.serviceShowcase.map((item,i)=>i===index?{...item,tagline:e.target.value}:item)}))}/></label><label>Image description<input value={service.alt} onChange={e=>setContent(current=>({...current,serviceShowcase:current.serviceShowcase.map((item,i)=>i===index?{...item,alt:e.target.value}:item)}))}/></label></div><button type="button" onClick={()=>setContent(current=>({...current,serviceShowcase:current.serviceShowcase.filter((_,i)=>i!==index)}))}><i className="fa-solid fa-trash-can"/> Remove</button></article>)}</div><button type="button" className="website-add-row" onClick={()=>setContent(current=>({...current,serviceShowcase:[...current.serviceShowcase,{name:"New service",tagline:"Describe this service.",image:"",alt:"New service"}]}))}><i className="fa-solid fa-plus"/> Add service card</button><p className="website-hint">These cards control the landing-page showcase. Prices and actual bookable services remain managed in Pricing.</p></section>
    <section><h3>Meet Dr. Kharyl</h3><div className="website-copy-grid"><label>Section label<input value={content.doctorEyebrow} onChange={e=>field("doctorEyebrow",e.target.value)}/></label><label>Name<input value={content.doctorName} onChange={e=>field("doctorName",e.target.value)}/></label><label>Professional title<input value={content.doctorTitle} onChange={e=>field("doctorTitle",e.target.value)}/></label><label className="wide">Biography<textarea value={content.doctorBio} onChange={e=>field("doctorBio",e.target.value)}/></label></div><label className="website-upload"><i className="fa-solid fa-user-doctor"/><span>{uploading==="doctor"?"Uploading...":"Upload doctor photo"}</span><input type="file" accept="image/*" disabled={Boolean(uploading)} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0],"doctor")}/></label>{content.doctorPhoto&&<img className="website-doctor-preview" src={content.doctorPhoto} alt="Doctor preview"/>}</section>
    <section><h3>Social posts</h3><div className="website-copy-grid"><label>Section heading<input value={content.socialHeading} onChange={e=>field("socialHeading",e.target.value)}/></label><label>Facebook page URL<input type="url" value={content.facebookPageUrl} onChange={e=>field("facebookPageUrl",e.target.value)}/></label><label>Instagram page URL<input type="url" value={content.instagramUrl} onChange={e=>field("instagramUrl",e.target.value)}/></label></div><p className="website-hint">Facebook posts must be Public to appear as embeds. Known Facebook share links are converted to their permanent post URL when published. Instagram posts remain clickable links.</p><div className="website-faq-editor website-social-editor">{content.socialPosts.map((post,index)=><article key={index}><label>Post title<input value={post.title} onChange={e=>setContent(current=>({...current,socialPosts:current.socialPosts.map((item,i)=>i===index?{...item,title:e.target.value}:item)}))}/></label><label>Public post URL<input type="url" value={post.url} onChange={e=>setContent(current=>({...current,socialPosts:current.socialPosts.map((item,i)=>i===index?{...item,url:e.target.value}:item)}))} onBlur={e=>setContent(current=>({...current,socialPosts:current.socialPosts.map((item,i)=>i===index?{...item,url:normalizeFacebookPostUrl(e.target.value)}:item)}))}/></label><label>Platform<select value={post.platform} onChange={e=>setContent(current=>({...current,socialPosts:current.socialPosts.map((item,i)=>i===index?{...item,platform:e.target.value as "facebook"|"instagram"}:item)}))}><option value="facebook">Facebook</option><option value="instagram">Instagram</option></select></label><button type="button" onClick={()=>setContent(current=>({...current,socialPosts:current.socialPosts.filter((_,i)=>i!==index)}))}><i className="fa-solid fa-trash-can"/> Remove</button></article>)}</div><button type="button" className="website-add-row" onClick={()=>setContent(current=>({...current,socialPosts:[...current.socialPosts,{title:"New social post",url:"",platform:"facebook"}]}))}><i className="fa-solid fa-plus"/> Add social post</button></section>
    <section><h3>Moving results gallery</h3><p>Upload clinic photos, before-and-after results, GIFs, and short videos. They appear in the continuously moving results board after Services.</p><div className="website-copy-grid"><label>Section label<input value={content.galleryEyebrow} onChange={e=>field("galleryEyebrow",e.target.value)}/></label><label>Heading<input value={content.galleryTitle} onChange={e=>field("galleryTitle",e.target.value)}/></label><label className="wide">Description<textarea value={content.galleryDescription} onChange={e=>field("galleryDescription",e.target.value)}/></label><label>Board badge<input value={content.galleryBadge} onChange={e=>field("galleryBadge",e.target.value)}/></label></div><label className="website-upload"><i className="fa-solid fa-images"/><span>{uploading==="gallery"?"Uploading...":"Add gallery media"}</span><input type="file" accept="image/*,video/mp4,video/webm" disabled={Boolean(uploading)} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0],"gallery")}/></label><MediaList items={content.galleryMedia} onRemove={i=>remove("gallery",i)}/></section>
    <section><h3>Frequently asked questions</h3><div className="website-faq-editor">{content.faqs.map((faq,index)=><article key={index}><label>Question<input value={faq.question} onChange={e=>setContent(current=>({...current,faqs:current.faqs.map((item,i)=>i===index?{...item,question:e.target.value}:item)}))}/></label><label>Answer<textarea value={faq.answer} onChange={e=>setContent(current=>({...current,faqs:current.faqs.map((item,i)=>i===index?{...item,answer:e.target.value}:item)}))}/></label><button type="button" onClick={()=>setContent(current=>({...current,faqs:current.faqs.filter((_,i)=>i!==index)}))}><i className="fa-solid fa-trash-can"/> Remove</button></article>)}</div><button type="button" className="website-add-row" onClick={()=>setContent(current=>({...current,faqs:[...current.faqs,{question:"",answer:""}]}))}><i className="fa-solid fa-plus"/> Add FAQ</button></section>
    <section><h3>Contact, location, and footer</h3><div className="website-copy-grid"><label>Contact label<input value={content.contactEyebrow} onChange={e=>field("contactEyebrow",e.target.value)}/></label><label>Contact heading<input value={content.contactTitle} onChange={e=>field("contactTitle",e.target.value)}/></label><label className="wide">Contact introduction<textarea value={content.contactBody} onChange={e=>field("contactBody",e.target.value)}/></label><label>Phone<input value={content.phone} onChange={e=>field("phone",e.target.value)}/></label><label>Email<input type="email" value={content.email} onChange={e=>field("email",e.target.value)}/></label><label>Address<input value={content.address} onChange={e=>field("address",e.target.value)}/></label><label>Clinic hours<input value={content.clinicHours} onChange={e=>field("clinicHours",e.target.value)}/></label><label className="wide">Footer tagline<input value={content.footerTagline} onChange={e=>field("footerTagline",e.target.value)}/></label></div></section>
  </div>;
}
type MediaAction=number|{from:number;to:number};
function MediaList({items,onRemove}:{items:LandingMedia[];onRemove:(action:MediaAction)=>void}){
  const [dragging,setDragging]=useState<number|null>(null);
  return <div className="website-media-list">{items.map((item,index)=><article key={item.url} draggable className={dragging===index?"dragging":""} onDragStart={event=>{setDragging(index);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",String(index));}} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="move";}} onDrop={event=>{event.preventDefault();const from=Number(event.dataTransfer.getData("text/plain"));if(Number.isInteger(from)&&from!==index)onRemove({from,to:index});setDragging(null);}} onDragEnd={()=>setDragging(null)}>
    <div className="website-media-drag"><i className="fa-solid fa-grip-vertical"/><span>Drag to reorder</span></div>
    {item.type==="video"?<video src={item.url} muted/>:<img src={item.url} alt={item.alt}/>}<span>{index+1}. {item.alt}</span>
    <div className="website-media-actions"><button type="button" disabled={index===0} onClick={()=>onRemove({from:index,to:index-1})} aria-label="Move media earlier"><i className="fa-solid fa-arrow-left"/></button><button type="button" disabled={index===items.length-1} onClick={()=>onRemove({from:index,to:index+1})} aria-label="Move media later"><i className="fa-solid fa-arrow-right"/></button><button type="button" className="remove" onClick={()=>onRemove(index)} aria-label="Remove media"><i className="fa-solid fa-trash-can"/></button></div>
  </article>)}</div>;
}
