"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { normalizeFacebookPostUrl, normalizeLandingSocialContent } from "@/lib/landing-social";

export type LandingMedia = { url: string; type: "image" | "video"; alt: string; title?: string };
export type LandingFaq = { question:string; answer:string };
export type LandingSocialPost = { title:string; url:string; platform:"facebook"|"instagram" };
export type LandingServiceCard = { name:string; tagline:string; image:string; alt:string };
export type LandingServiceIcon = { name:string; category:string; image:string; alt:string };
export const LANDING_FONT_OPTIONS = [
  { value:"default", label:"Klinique signature", description:"The current mix of elegant serif, clean sans serif, and cursive accents." },
  { value:"elegant", label:"Elegant serif", description:"Cormorant Garamond throughout for a refined editorial look." },
  { value:"modern", label:"Modern sans serif", description:"Jost throughout for a clean and contemporary look." },
  { value:"cursive", label:"Cursive", description:"Allura throughout for a handwritten, decorative look." },
  { value:"classic", label:"Classic", description:"Georgia throughout for a familiar, highly readable style." },
  { value:"clean", label:"Clean", description:"Arial throughout for simple, accessible text." },
] as const;
export type LandingFont = typeof LANDING_FONT_OPTIONS[number]["value"];
export function normalizeLandingFont(value: unknown): LandingFont {
  return LANDING_FONT_OPTIONS.some(option=>option.value===value) ? value as LandingFont : "default";
}
export type LandingTextFonts = Record<string, LandingFont>;
export const DEFAULT_SERVICE_ICONS:LandingServiceIcon[]=[{image:"/images/botox-removebg-preview.png",alt:"Botox",name:"Botox & Neuromodulators",category:"Botox & Neuromodulators"},{image:"/images/fillers-removebg-preview.png",alt:"Fillers",name:"Fillers",category:"Fillers"},{image:"/images/skinboosters-removebg-preview.png",alt:"Skin Boosters",name:"Skin Boosters",category:"Skin Boosters"},{image:"/images/lasers-removebg-preview.png",alt:"Lasers",name:"Lasers & Skin Rejuvenation",category:"Laser Treatments"},{image:"/images/facialandskin-removebg-preview.png",alt:"Facial & Skin",name:"Facial & Skin Treatments",category:"Facial & Skin Treatments"},{image:"/images/IV_teraphy-removebg-preview.png",alt:"IV Therapy",name:"IV Therapy & Wellness",category:"IV Therapy & Wellness"},{image:"/images/otherservices-removebg-preview.png",alt:"Other Services",name:"Other Services",category:""}];
export type ContentTab = "home"|"about"|"services"|"doctor"|"social"|"gallery"|"faq"|"contact";
export const DEFAULT_NAVIGATION_ORDER:ContentTab[]=["home","about","services","doctor","social","gallery","faq","contact"];
export type LandingContent = { textFonts:LandingTextFonts;heroEyebrow:string;heroTitle:string;heroSubtitle:string;heroDescription:string;doctorEyebrow:string;doctorName:string;doctorTitle:string;doctorBio:string;doctorPhoto:string;socialHeading:string;socialPostUrl:string;facebookPageUrl:string;instagramUrl:string;aboutEyebrow:string;aboutTitle:string;aboutBody:string;aboutImage:string;servicesEyebrow:string;servicesTitle:string;galleryEyebrow:string;galleryTitle:string;galleryDescription:string;galleryBadge:string;quoteText:string;quoteSubtitle:string;contactEyebrow:string;contactTitle:string;contactBody:string;phone:string;email:string;address:string;clinicHours:string;footerTagline:string;heroMedia:LandingMedia[];galleryMedia:LandingMedia[];faqs:LandingFaq[];socialPosts:LandingSocialPost[];serviceShowcase:LandingServiceCard[];serviceIcons:LandingServiceIcon[];navigationOrder:ContentTab[] };
const empty: LandingContent = { textFonts:{},heroEyebrow:"",heroTitle:"",heroSubtitle:"",heroDescription:"",doctorEyebrow:"",doctorName:"",doctorTitle:"",doctorBio:"",doctorPhoto:"",socialHeading:"",socialPostUrl:"",facebookPageUrl:"",instagramUrl:"",aboutEyebrow:"",aboutTitle:"",aboutBody:"",aboutImage:"",servicesEyebrow:"",servicesTitle:"",galleryEyebrow:"",galleryTitle:"",galleryDescription:"",galleryBadge:"",quoteText:"",quoteSubtitle:"",contactEyebrow:"",contactTitle:"",contactBody:"",phone:"",email:"",address:"",clinicHours:"",footerTagline:"",heroMedia:[],galleryMedia:[],faqs:[],socialPosts:[],serviceShowcase:[],serviceIcons:DEFAULT_SERVICE_ICONS,navigationOrder:DEFAULT_NAVIGATION_ORDER };

async function token() { const { data } = await supabase.auth.getSession(); if (!data.session) throw new Error("Your session expired."); return data.session.access_token; }
export default function WebsiteContentManager() {
  const [content,setContent]=useState<LandingContent>(empty); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const [tab,setTab]=useState<ContentTab>("home");
  const [draggingTab,setDraggingTab]=useState<ContentTab|null>(null);
  useEffect(()=>{ void fetch("/api/landing-content").then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error);setContent(normalizeLandingSocialContent({...empty,...x.content,textFonts:x.content?.textFonts||{},heroMedia:x.content?.heroMedia||[],galleryMedia:x.content?.galleryMedia||[],faqs:x.content?.faqs||[],socialPosts:x.content?.socialPosts||[],serviceShowcase:x.content?.serviceShowcase||[],serviceIcons:x.content?.serviceIcons||DEFAULT_SERVICE_ICONS,navigationOrder:x.content?.navigationOrder||DEFAULT_NAVIGATION_ORDER}));}).catch(e=>setError(e.message)).finally(()=>setLoading(false)); },[]);
  const field=(key:keyof LandingContent,value:string)=>setContent(current=>({...current,[key]:value}));
  async function save(){setSaving(true);setError("");setMessage("");try{const normalized=normalizeLandingSocialContent(content);const response=await fetch("/api/landing-content",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await token()}`},body:JSON.stringify({content:normalized})});const result=await response.json();if(!response.ok)throw new Error(result.error);setContent({...empty,...result.content});setMessage("Landing-page content published.");}catch(e){setError(e instanceof Error?e.message:"Unable to save.");}finally{setSaving(false);}}
  async function upload(file:File,target:"hero"|"gallery"|"doctor"|"about"|"service"|"serviceIcon",serviceIndex?:number){if(target==="hero"&&content.heroMedia.length>=5)return setError("The hero carousel supports up to five media items.");setUploading(target==="service"?`service-${serviceIndex}`:target==="serviceIcon"?`service-icon-${serviceIndex}`:target);setError("");try{const form=new FormData();form.append("file",file);const response=await fetch("/api/landing-content",{method:"POST",headers:{Authorization:`Bearer ${await token()}`},body:form});const media=await response.json();if(!response.ok)throw new Error(media.error);setContent(current=>target==="doctor"?{...current,doctorPhoto:media.url}:target==="about"?{...current,aboutImage:media.url}:target==="hero"?{...current,heroMedia:[...current.heroMedia,media]}:target==="service"&&serviceIndex!==undefined?{...current,serviceShowcase:current.serviceShowcase.map((item,index)=>index===serviceIndex?{...item,image:media.url,alt:item.alt||item.name}:item)}:target==="serviceIcon"&&serviceIndex!==undefined?{...current,serviceIcons:current.serviceIcons.map((item,index)=>index===serviceIndex?{...item,image:media.url,alt:item.alt||item.name}:item)}:{...current,galleryMedia:[...current.galleryMedia,{...media,title:""}]});setMessage("Media uploaded. Add a display title, then click Publish changes to make it live.");}catch(e){setError(e instanceof Error?e.message:"Upload failed.");}finally{setUploading("");}}
  const changeMedia=(target:"hero"|"gallery",action:number|{from:number;to:number})=>setContent(current=>{const key=target==="hero"?"heroMedia":"galleryMedia";const items=[...current[key]];if(typeof action==="number")items.splice(action,1);else{const [moved]=items.splice(action.from,1);items.splice(action.to,0,moved);}return{...current,[key]:items};});
  const moveService=(from:number,to:number)=>setContent(current=>{const items=[...current.serviceShowcase];const[moved]=items.splice(from,1);items.splice(to,0,moved);return{...current,serviceShowcase:items};});
  const setTextFont=(key:string,font:LandingFont)=>setContent(current=>({...current,textFonts:{...current.textFonts,[key]:font}}));
  const remove=changeMedia;
  if(loading)return <div className="staff-settings__loading"><i className="fa-solid fa-spinner fa-spin"/> Loading website content...</div>;
  const tabs:{key:ContentTab;label:string;description:string;icon:string}[]=[{key:"home",label:"Home",description:"Hero carousel",icon:"fa-house"},{key:"about",label:"About",description:"Clinic introduction",icon:"fa-spa"},{key:"services",label:"Services",description:"Cards, images, and copy",icon:"fa-syringe"},{key:"doctor",label:"Doctor",description:"Dr. Kharyl profile",icon:"fa-user-doctor"},{key:"social",label:"Social",description:"Social media posts",icon:"fa-share-nodes"},{key:"gallery",label:"Gallery",description:"Moving results board",icon:"fa-images"},{key:"faq",label:"FAQ",description:"Questions and answers",icon:"fa-circle-question"},{key:"contact",label:"Contact & Footer",description:"Details and footer",icon:"fa-address-card"}];
  const orderedTabs=[...tabs].sort((a,b)=>content.navigationOrder.indexOf(a.key)-content.navigationOrder.indexOf(b.key));
  const moveTab=(from:ContentTab,to:ContentTab)=>setContent(current=>{const order=[...current.navigationOrder],fromIndex=order.indexOf(from),toIndex=order.indexOf(to);if(fromIndex<0||toIndex<0)return current;const[moved]=order.splice(fromIndex,1);order.splice(toIndex,0,moved);return{...current,navigationOrder:order}});
  return <div className={`website-content-manager tab-${tab}`}><header><div><p>WEBSITE CONTENT</p><h2>Landing-page editor</h2><span>Choose a section below, edit its content, then publish your changes.</span><a className="website-preview-link" href="/" target="_blank">Preview landing page <i className="fa-solid fa-arrow-up-right-from-square"/></a></div><button onClick={()=>void save()} disabled={saving}>{saving?"Publishing...":"Publish changes"}</button></header>{error&&<p className="account-alert error">{error}</p>}{message&&<p className="account-alert success">{message}</p>}<nav className="website-content-tabs" aria-label="Landing page navigation order">{orderedTabs.map(item=><button type="button" draggable key={item.key} className={`${tab===item.key?"active":""} ${draggingTab===item.key?"dragging":""}`} onClick={()=>setTab(item.key)} onDragStart={event=>{setDraggingTab(item.key);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",item.key)}} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="move"}} onDrop={event=>{event.preventDefault();const from=event.dataTransfer.getData("text/plain") as ContentTab;if(DEFAULT_NAVIGATION_ORDER.includes(from))moveTab(from,item.key);setDraggingTab(null)}} onDragEnd={()=>setDraggingTab(null)}><i className="fa-solid fa-grip-vertical website-tab-grip"/><i className={`fa-solid ${item.icon}`}/><span><strong>{item.label}</strong><small>{item.description}</small></span></button>)}</nav>
    {tab==="services"&&<ServiceIconEditor items={content.serviceIcons} fonts={content.textFonts} uploading={uploading} onFontChange={setTextFont} onChange={items=>setContent(current=>({...current,serviceIcons:items}))} onUpload={(file,index)=>void upload(file,"serviceIcon",index)}/>}
    <section><h3>Hero carousel</h3><p>Upload up to five images, GIFs, or videos.</p><div className="website-copy-grid"><TextField label="Headline" fieldKey="heroTitle" value={content.heroTitle} font={content.textFonts.heroTitle} onChange={value=>field("heroTitle",value)} onFontChange={setTextFont}/><TextField label="Eyebrow" fieldKey="heroEyebrow" value={content.heroEyebrow} font={content.textFonts.heroEyebrow} onChange={value=>field("heroEyebrow",value)} onFontChange={setTextFont}/><TextField label="Subtitle" fieldKey="heroSubtitle" value={content.heroSubtitle} font={content.textFonts.heroSubtitle} onChange={value=>field("heroSubtitle",value)} onFontChange={setTextFont}/><TextField wide multiline label="Description" fieldKey="heroDescription" value={content.heroDescription} font={content.textFonts.heroDescription} onChange={value=>field("heroDescription",value)} onFontChange={setTextFont}/></div><label className="website-upload"><i className="fa-solid fa-cloud-arrow-up"/><span>{uploading==="hero"?"Uploading...":"Add hero media"}</span><input type="file" accept="image/*,video/mp4,video/webm" disabled={Boolean(uploading)||content.heroMedia.length>=5} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0],"hero")}/></label><MediaList items={content.heroMedia} onRemove={i=>remove("hero",i)}/></section>
    <section><h3>About section</h3><div className="website-copy-grid"><TextField label="Section label" fieldKey="aboutEyebrow" value={content.aboutEyebrow} font={content.textFonts.aboutEyebrow} onChange={value=>field("aboutEyebrow",value)} onFontChange={setTextFont}/><TextField label="Heading" fieldKey="aboutTitle" value={content.aboutTitle} font={content.textFonts.aboutTitle} onChange={value=>field("aboutTitle",value)} onFontChange={setTextFont}/><TextField wide multiline label="Description" fieldKey="aboutBody" value={content.aboutBody} font={content.textFonts.aboutBody} onChange={value=>field("aboutBody",value)} onFontChange={setTextFont}/></div>{content.aboutImage&&<div className="website-current-image"><span>Current about image</span><img src={content.aboutImage} alt="Current About section"/></div>}<label className="website-upload"><i className="fa-solid fa-image"/><span>{uploading==="about"?"Uploading...":"Replace about photo"}</span><input type="file" accept="image/*" disabled={Boolean(uploading)} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0],"about")}/></label></section>
    <section><h3>Services showcase</h3><p>Drag the cards by their handles to change their order on the landing page.</p>
      <div className="website-copy-grid"><TextField label="Services label" fieldKey="servicesEyebrow" value={content.servicesEyebrow} font={content.textFonts.servicesEyebrow} onChange={value=>field("servicesEyebrow",value)} onFontChange={setTextFont}/><TextField label="Services heading" fieldKey="servicesTitle" value={content.servicesTitle} font={content.textFonts.servicesTitle} onChange={value=>field("servicesTitle",value)} onFontChange={setTextFont}/><TextField label="Quote banner" fieldKey="quoteText" value={content.quoteText} font={content.textFonts.quoteText} onChange={value=>field("quoteText",value)} onFontChange={setTextFont}/><TextField label="Quote subtitle" fieldKey="quoteSubtitle" value={content.quoteSubtitle} font={content.textFonts.quoteSubtitle} onChange={value=>field("quoteSubtitle",value)} onFontChange={setTextFont}/></div>
      <div className="website-service-editor">{content.serviceShowcase.map((service,index)=><article key={`${service.name}-${index}`} draggable onDragStart={event=>{event.dataTransfer.setData("text/service-card",String(index));event.currentTarget.classList.add("dragging")}} onDragEnd={event=>event.currentTarget.classList.remove("dragging")} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();const from=Number(event.dataTransfer.getData("text/service-card"));if(Number.isInteger(from)&&from!==index)moveService(from,index)}}>
        <div className="website-service-drag"><i className="fa-solid fa-grip-vertical"/><span>{index+1}</span><strong>Drag to reorder</strong></div>
        <div className="website-service-image">{service.image?<img src={service.image} alt={service.alt||service.name}/>:<i className="fa-solid fa-image"/>}<label><i className="fa-solid fa-camera"/> {uploading===`service-${index}`?"Uploading...":"Change image"}<input type="file" accept="image/*" disabled={Boolean(uploading)} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0],"service",index)}/></label></div>
        <div><TextField label="Service name / type" fieldKey={`service.${index}.name`} value={service.name} font={content.textFonts[`service.${index}.name`]} onChange={value=>setContent(current=>({...current,serviceShowcase:current.serviceShowcase.map((item,i)=>i===index?{...item,name:value,alt:item.alt||value}:item)}))} onFontChange={setTextFont}/><TextField label="Tagline" fieldKey={`service.${index}.tagline`} value={service.tagline} font={content.textFonts[`service.${index}.tagline`]} onChange={value=>setContent(current=>({...current,serviceShowcase:current.serviceShowcase.map((item,i)=>i===index?{...item,tagline:value}:item)}))} onFontChange={setTextFont}/><label>Image description<input value={service.alt} onChange={e=>setContent(current=>({...current,serviceShowcase:current.serviceShowcase.map((item,i)=>i===index?{...item,alt:e.target.value}:item)}))}/></label></div>
        <div className="website-service-actions"><button type="button" disabled={index===0} onClick={()=>moveService(index,index-1)}><i className="fa-solid fa-arrow-left"/></button><button type="button" disabled={index===content.serviceShowcase.length-1} onClick={()=>moveService(index,index+1)}><i className="fa-solid fa-arrow-right"/></button><button type="button" className="remove" onClick={()=>setContent(current=>({...current,serviceShowcase:current.serviceShowcase.filter((_,i)=>i!==index)}))}><i className="fa-solid fa-trash-can"/> Remove</button></div>
      </article>)}</div><button type="button" className="website-add-row" onClick={()=>setContent(current=>({...current,serviceShowcase:[...current.serviceShowcase,{name:"New service",tagline:"Describe this service.",image:"",alt:"New service"}]}))}><i className="fa-solid fa-plus"/> Add service card</button><p className="website-hint">The saved order is used on the landing page. Prices and actual bookable services remain managed in Pricing.</p></section>
    <section><h3>Meet Dr. Kharyl</h3><div className="website-copy-grid"><TextField label="Section label" fieldKey="doctorEyebrow" value={content.doctorEyebrow} font={content.textFonts.doctorEyebrow} onChange={value=>field("doctorEyebrow",value)} onFontChange={setTextFont}/><TextField label="Name" fieldKey="doctorName" value={content.doctorName} font={content.textFonts.doctorName} onChange={value=>field("doctorName",value)} onFontChange={setTextFont}/><TextField label="Professional title" fieldKey="doctorTitle" value={content.doctorTitle} font={content.textFonts.doctorTitle} onChange={value=>field("doctorTitle",value)} onFontChange={setTextFont}/><TextField wide multiline label="Biography" fieldKey="doctorBio" value={content.doctorBio} font={content.textFonts.doctorBio} onChange={value=>field("doctorBio",value)} onFontChange={setTextFont}/></div><label className="website-upload"><i className="fa-solid fa-user-doctor"/><span>{uploading==="doctor"?"Uploading...":"Upload doctor photo"}</span><input type="file" accept="image/*" disabled={Boolean(uploading)} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0],"doctor")}/></label>{content.doctorPhoto&&<img className="website-doctor-preview" src={content.doctorPhoto} alt="Doctor preview"/>}</section>
    <section>
      <h3>Social posts</h3>
      <div className="website-copy-grid">
        <TextField label="Section heading" fieldKey="socialHeading" value={content.socialHeading} font={content.textFonts.socialHeading} onChange={value=>field("socialHeading",value)} onFontChange={setTextFont}/>
        <label>Facebook page URL<input type="url" value={content.facebookPageUrl} onChange={e=>field("facebookPageUrl",e.target.value)}/></label>
        <label>Instagram page URL<input type="url" value={content.instagramUrl} onChange={e=>field("instagramUrl",e.target.value)}/></label>
      </div>
      <p className="website-hint">Facebook posts must be Public to appear as embeds. Known Facebook share links are converted to their permanent post URL when published. Instagram posts remain clickable links.</p>
      <div className="website-faq-editor website-social-editor">{content.socialPosts.map((post,index)=><article key={index}>
        <TextField label="Post title" fieldKey={`social.${index}.title`} value={post.title} font={content.textFonts[`social.${index}.title`]} onChange={value=>setContent(current=>({...current,socialPosts:current.socialPosts.map((item,i)=>i===index?{...item,title:value}:item)}))} onFontChange={setTextFont}/>
        <label>Public post URL<input type="url" value={post.url} onChange={e=>setContent(current=>({...current,socialPosts:current.socialPosts.map((item,i)=>i===index?{...item,url:e.target.value}:item)}))} onBlur={e=>setContent(current=>({...current,socialPosts:current.socialPosts.map((item,i)=>i===index?{...item,url:normalizeFacebookPostUrl(e.target.value)}:item)}))}/></label>
        <label>Platform<select value={post.platform} onChange={e=>setContent(current=>({...current,socialPosts:current.socialPosts.map((item,i)=>i===index?{...item,platform:e.target.value as "facebook"|"instagram"}:item)}))}><option value="facebook">Facebook</option><option value="instagram">Instagram</option></select></label>
        <button type="button" onClick={()=>setContent(current=>({...current,socialPosts:current.socialPosts.filter((_,i)=>i!==index)}))}><i className="fa-solid fa-trash-can"/> Remove</button>
      </article>)}</div>
      <button type="button" className="website-add-row" onClick={()=>setContent(current=>({...current,socialPosts:[...current.socialPosts,{title:"New social post",url:"",platform:"facebook"}]}))}><i className="fa-solid fa-plus"/> Add social post</button>
    </section>
    <section><h3>Moving results gallery</h3><p>Upload clinic photos, before-and-after results, GIFs, and short videos. They appear in the continuously moving results board after Services.</p><div className="website-copy-grid"><TextField label="Section label" fieldKey="galleryEyebrow" value={content.galleryEyebrow} font={content.textFonts.galleryEyebrow} onChange={value=>field("galleryEyebrow",value)} onFontChange={setTextFont}/><TextField label="Heading" fieldKey="galleryTitle" value={content.galleryTitle} font={content.textFonts.galleryTitle} onChange={value=>field("galleryTitle",value)} onFontChange={setTextFont}/><TextField wide multiline label="Description" fieldKey="galleryDescription" value={content.galleryDescription} font={content.textFonts.galleryDescription} onChange={value=>field("galleryDescription",value)} onFontChange={setTextFont}/><TextField label="Board badge" fieldKey="galleryBadge" value={content.galleryBadge} font={content.textFonts.galleryBadge} onChange={value=>field("galleryBadge",value)} onFontChange={setTextFont}/></div><label className="website-upload"><i className="fa-solid fa-images"/><span>{uploading==="gallery"?"Uploading...":"Add gallery media"}</span><input type="file" accept="image/*,video/mp4,video/webm" disabled={Boolean(uploading)} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0],"gallery")}/></label><MediaList items={content.galleryMedia} fonts={content.textFonts} onFontChange={setTextFont} onRemove={i=>remove("gallery",i)} onTitleChange={(index,title)=>setContent(current=>({...current,galleryMedia:current.galleryMedia.map((item,i)=>i===index?{...item,title}:item)}))}/></section>
    <section><h3>Frequently asked questions</h3><div className="website-faq-editor">{content.faqs.map((faq,index)=><article key={index}><TextField label="Question" fieldKey={`faq.${index}.question`} value={faq.question} font={content.textFonts[`faq.${index}.question`]} onChange={value=>setContent(current=>({...current,faqs:current.faqs.map((item,i)=>i===index?{...item,question:value}:item)}))} onFontChange={setTextFont}/><TextField multiline label="Answer" fieldKey={`faq.${index}.answer`} value={faq.answer} font={content.textFonts[`faq.${index}.answer`]} onChange={value=>setContent(current=>({...current,faqs:current.faqs.map((item,i)=>i===index?{...item,answer:value}:item)}))} onFontChange={setTextFont}/><button type="button" onClick={()=>setContent(current=>({...current,faqs:current.faqs.filter((_,i)=>i!==index)}))}><i className="fa-solid fa-trash-can"/> Remove</button></article>)}</div><button type="button" className="website-add-row" onClick={()=>setContent(current=>({...current,faqs:[...current.faqs,{question:"",answer:""}]}))}><i className="fa-solid fa-plus"/> Add FAQ</button></section>
    <section><h3>Contact, location, and footer</h3><div className="website-copy-grid"><TextField label="Contact label" fieldKey="contactEyebrow" value={content.contactEyebrow} font={content.textFonts.contactEyebrow} onChange={value=>field("contactEyebrow",value)} onFontChange={setTextFont}/><TextField label="Contact heading" fieldKey="contactTitle" value={content.contactTitle} font={content.textFonts.contactTitle} onChange={value=>field("contactTitle",value)} onFontChange={setTextFont}/><TextField wide multiline label="Contact introduction" fieldKey="contactBody" value={content.contactBody} font={content.textFonts.contactBody} onChange={value=>field("contactBody",value)} onFontChange={setTextFont}/><TextField label="Phone" fieldKey="phone" value={content.phone} font={content.textFonts.phone} onChange={value=>field("phone",value)} onFontChange={setTextFont}/><TextField label="Email" fieldKey="email" type="email" value={content.email} font={content.textFonts.email} onChange={value=>field("email",value)} onFontChange={setTextFont}/><TextField label="Address" fieldKey="address" value={content.address} font={content.textFonts.address} onChange={value=>field("address",value)} onFontChange={setTextFont}/><TextField label="Clinic hours" fieldKey="clinicHours" value={content.clinicHours} font={content.textFonts.clinicHours} onChange={value=>field("clinicHours",value)} onFontChange={setTextFont}/><TextField wide label="Footer tagline" fieldKey="footerTagline" value={content.footerTagline} font={content.textFonts.footerTagline} onChange={value=>field("footerTagline",value)} onFontChange={setTextFont}/></div></section>
  </div>;
}
function FontPicker({value,onChange}:{value:LandingFont;onChange:(font:LandingFont)=>void}){
  return <span className="website-font-picker" title="Change this text's font"><i className="fa-solid fa-font"/><select aria-label="Font for this text" value={value} onClick={event=>event.stopPropagation()} onChange={event=>onChange(normalizeLandingFont(event.target.value))}>{LANDING_FONT_OPTIONS.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></span>;
}
function TextField({label,fieldKey,value,font,onChange,onFontChange,wide=false,multiline=false,type="text",className}:{label:string;fieldKey:string;value:string;font?:LandingFont;onChange:(value:string)=>void;onFontChange:(key:string,font:LandingFont)=>void;wide?:boolean;multiline?:boolean;type?:string;className?:string}){
  const selected=normalizeLandingFont(font);
  return <label className={[wide?"wide":"",className||""].filter(Boolean).join(" ")||undefined}><span className="website-field-heading">{label}<FontPicker value={selected} onChange={next=>onFontChange(fieldKey,next)}/></span>{multiline?<textarea className={`text-font-${selected}`} value={value} onChange={event=>onChange(event.target.value)}/>:<input type={type} className={`text-font-${selected}`} value={value} onChange={event=>onChange(event.target.value)}/>}</label>;
}
type MediaAction=number|{from:number;to:number};
function ServiceIconEditor({items,fonts,uploading,onChange,onUpload,onFontChange}:{items:LandingServiceIcon[];fonts:LandingTextFonts;uploading:string;onChange:(items:LandingServiceIcon[])=>void;onUpload:(file:File,index:number)=>void;onFontChange:(key:string,font:LandingFont)=>void}){
 const[dragging,setDragging]=useState<number|null>(null),[dragOver,setDragOver]=useState<number|null>(null);
 const move=(from:number,to:number)=>{if(to<0||to>=items.length)return;const next=[...items],[item]=next.splice(from,1);next.splice(to,0,item);onChange(next)};
 const update=(index:number,values:Partial<LandingServiceIcon>)=>onChange(items.map((item,i)=>i===index?{...item,...values}:item));
 return <div className="website-service-icons-editor"><header><div><p>SERVICE SHORTCUTS</p><h3>Circular service menu</h3><span>Drag shortcuts into position, then publish to update the landing page.</span></div><button type="button" onClick={()=>onChange([...items,{name:"New service",category:"",image:"",alt:"New service icon"}])}><i className="fa-solid fa-plus"/> Add shortcut</button></header><div>{items.map((item,index)=><article key={`${item.name}-${index}`} className={`${dragging===index?"dragging":""} ${dragOver===index?"drag-over":""}`} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="move";setDragOver(index)}} onDragLeave={()=>setDragOver(value=>value===index?null:value)} onDrop={event=>{event.preventDefault();const from=Number(event.dataTransfer.getData("text/plain"));if(Number.isInteger(from)&&from!==index)move(from,index);setDragging(null);setDragOver(null)}}><div className="website-icon-drag" draggable onDragStart={event=>{setDragging(index);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",String(index))}} onDragEnd={()=>{setDragging(null);setDragOver(null)}}><i className="fa-solid fa-grip-vertical"/><span>{index+1}</span><strong>Drag to reorder</strong></div><div className="website-icon-preview">{item.image?<img src={item.image} alt={item.alt||item.name}/>:<i className="fa-solid fa-spa"/>}<label><i className={`fa-solid ${uploading===`service-icon-${index}`?"fa-spinner fa-spin":"fa-camera"}`}/><input type="file" accept="image/*" disabled={Boolean(uploading)} onChange={event=>event.target.files?.[0]&&onUpload(event.target.files[0],index)}/></label></div><div className="website-icon-fields"><TextField label="Display name" fieldKey={`serviceIcon.${index}.name`} value={item.name} font={fonts[`serviceIcon.${index}.name`]} onChange={value=>update(index,{name:value})} onFontChange={onFontChange}/><label>Booking category<input value={item.category} onChange={event=>update(index,{category:event.target.value})} placeholder="e.g. Botox"/></label><label>Image description<input value={item.alt} onChange={event=>update(index,{alt:event.target.value})}/></label></div><div className="website-icon-actions"><button type="button" disabled={index===0} onClick={()=>move(index,index-1)} aria-label="Move shortcut earlier"><i className="fa-solid fa-arrow-left"/></button><button type="button" disabled={index===items.length-1} onClick={()=>move(index,index+1)} aria-label="Move shortcut later"><i className="fa-solid fa-arrow-right"/></button><button type="button" className="remove" onClick={()=>onChange(items.filter((_,i)=>i!==index))}><i className="fa-solid fa-trash-can"/> Remove</button></div></article>)}</div></div>
}
function MediaList({items,fonts,onRemove,onTitleChange,onFontChange}:{items:LandingMedia[];fonts?:LandingTextFonts;onRemove:(action:MediaAction)=>void;onTitleChange?:(index:number,title:string)=>void;onFontChange?:(key:string,font:LandingFont)=>void}){
  const [dragging,setDragging]=useState<number|null>(null);
  return <div className="website-media-list">{items.map((item,index)=><article key={item.url} draggable className={dragging===index?"dragging":""} onDragStart={event=>{setDragging(index);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",String(index));}} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="move";}} onDrop={event=>{event.preventDefault();const from=Number(event.dataTransfer.getData("text/plain"));if(Number.isInteger(from)&&from!==index)onRemove({from,to:index});setDragging(null);}} onDragEnd={()=>setDragging(null)}>
    <div className="website-media-drag"><i className="fa-solid fa-grip-vertical"/><span>Drag to reorder</span></div>
    {item.type==="video"?<video src={item.url} muted/>:<img src={item.url} alt={item.alt}/>} {onTitleChange?<TextField className="website-media-title" label="Slide title" fieldKey={`gallery.${index}.title`} value={item.title||""} font={fonts?.[`gallery.${index}.title`]} onChange={title=>onTitleChange(index,title)} onFontChange={(key,font)=>onFontChange?.(key,font)}/>:<span>{index+1}. {item.alt}</span>}
    <div className="website-media-actions"><button type="button" disabled={index===0} onClick={()=>onRemove({from:index,to:index-1})} aria-label="Move media earlier"><i className="fa-solid fa-arrow-left"/></button><button type="button" disabled={index===items.length-1} onClick={()=>onRemove({from:index,to:index+1})} aria-label="Move media later"><i className="fa-solid fa-arrow-right"/></button><button type="button" className="remove" onClick={()=>onRemove(index)} aria-label="Remove media"><i className="fa-solid fa-trash-can"/></button></div>
  </article>)}</div>;
}
