import {createClient,type User} from "@supabase/supabase-js";
import {NextResponse} from "next/server";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,anonKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const admin=()=>{if(!url||!serviceKey)throw new Error("Supabase server credentials are not configured.");return createClient(url,serviceKey,{auth:{persistSession:false}})};
async function userFor(request:Request){const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token||!url||!anonKey)return null;const client=createClient(url,anonKey,{auth:{persistSession:false},global:{headers:{Authorization:`Bearer ${token}`}}});const{data}=await client.auth.getUser();return data.user}
async function staff(user:User|null){if(!user)return false;const{data}=await admin().from("profiles").select("role").eq("id",user.id).maybeSingle();return["doctor","superadmin","secretary"].includes(String(data?.role))}
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const fields="id,title,slug,excerpt,category,service_category_id,hero_url,hero_type,embed_url,blocks,status,featured,published_at,updated_at";
export async function GET(request:Request){try{const query=new URL(request.url).searchParams,manage=query.get("manage")==="1",slug=query.get("slug");const user=manage?await userFor(request):null;if(manage&&!await staff(user))return NextResponse.json({error:"Clinic staff access is required."},{status:403});let dbQuery=admin().from("blog_posts").select(fields).order("featured",{ascending:false}).order("published_at",{ascending:false,nullsFirst:false});if(!manage)dbQuery=dbQuery.eq("status","published");if(slug)dbQuery=dbQuery.eq("slug",slug);const{data,error}=await dbQuery;if(error)throw error;return NextResponse.json({posts:data||[]})}catch(error){console.error("Unable to load blog posts:",error);return NextResponse.json({error:"Unable to load blog posts. Apply the blog migration first."},{status:500})}}
export async function POST(request:Request){const user=await userFor(request);if(!await staff(user))return NextResponse.json({error:"Clinic staff access is required."},{status:403});try{const body=await request.json(),title=String(body.title||"Untitled article").trim(),slug=slugify(String(body.slug||title));const{data,error}=await admin().from("blog_posts").insert({title,slug,excerpt:String(body.excerpt||""),category:String(body.category||"Treatment Guide"),service_category_id:UUID.test(String(body.serviceCategoryId||""))?body.serviceCategoryId:null,hero_url:body.heroUrl||null,hero_type:body.heroType==="video"?"video":"image",embed_url:body.embedUrl||null,blocks:Array.isArray(body.blocks)?body.blocks:[],status:"draft",created_by:user!.id,updated_by:user!.id}).select(fields).single();if(error?.code==="23505")return NextResponse.json({error:"That article URL is already used."},{status:409});if(error)throw error;return NextResponse.json({post:data},{status:201})}catch(error){console.error("Unable to create blog post:",error);return NextResponse.json({error:"Unable to create the article."},{status:500})}}
export async function PATCH(request:Request){const user=await userFor(request);if(!await staff(user))return NextResponse.json({error:"Clinic staff access is required."},{status:403});try{const body=await request.json(),id=String(body.id||""),title=String(body.title||"").trim(),slug=slugify(String(body.slug||title)),status=["draft","published","archived"].includes(body.status)?body.status:"draft";if(!UUID.test(id)||!title||!slug)return NextResponse.json({error:"Article title and URL are required."},{status:400});const update={title,slug,excerpt:String(body.excerpt||""),category:String(body.category||"Treatment Guide"),service_category_id:UUID.test(String(body.serviceCategoryId||""))?body.serviceCategoryId:null,hero_url:body.heroUrl||null,hero_type:body.heroType==="video"?"video":"image",embed_url:body.embedUrl||null,blocks:Array.isArray(body.blocks)?body.blocks:[],status,featured:body.featured===true,published_at:status==="published"?(body.publishedAt||new Date().toISOString()):null,updated_by:user!.id,updated_at:new Date().toISOString()};const{data,error}=await admin().from("blog_posts").update(update).eq("id",id).select(fields).single();if(error?.code==="23505")return NextResponse.json({error:"That article URL is already used."},{status:409});if(error)throw error;return NextResponse.json({post:data})}catch(error){console.error("Unable to save blog post:",error);return NextResponse.json({error:"Unable to save the article."},{status:500})}}
export async function DELETE(request:Request){const user=await userFor(request);if(!await staff(user))return NextResponse.json({error:"Clinic staff access is required."},{status:403});const body=await request.json();if(!UUID.test(String(body.id||"")))return NextResponse.json({error:"Choose a valid article."},{status:400});const{error}=await admin().from("blog_posts").delete().eq("id",body.id);if(error)return NextResponse.json({error:"Unable to delete the article."},{status:500});return NextResponse.json({removed:true})}
